### PR TITLE
[WIP] [ADD] travis.yml

### PR DESCRIPTION
**Pull request by hbrunn**
I'm trying to figure out the best way to have travis for 8.0, I'll remove the WIP label when I'm satisfied

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
```
Your test run exceeded 50 minutes. 

One possible solution is to split up your test run.
```

now retrying without UNIT_TEST="1"

**Comment by rvalyi** [comment]
Hello @hbrunn,

I build time is a real issue, I also suggest skipping all l10n_\* modules. I don't know how much time you can save, but I think these modules don't test much as they mostly just load a huge chart of account. Instead, localizations tend to be better tested in their specific OCA repos with their specific extensions. So since we should probably make some sacrifice, I would choose that one.

**Comment by hbrunn** [comment]
thanks, good idea. With the regex-approach we can split up the modules to test as much as we want, but I also don't really see a point in testing those modules currently

**Comment by pedrobaeza** [comment]
I have checked and merge the MQT PR, and restart Travis. Let's see what we get.

**Comment by hbrunn** [comment]
It seems we have letigimate problems with `account_anglo_saxon` (https://travis-ci.org/OCA/OCB/jobs/49717399), `mrp_repair` & `mrp_byproduct` (https://travis-ci.org/OCA/OCB/jobs/49717403) and `point_of_sale` (https://travis-ci.org/OCA/OCB/jobs/49717405)

I'll look into `hr_timesheet_*` now, these values should be provided by some other module.

If somebody can point me to the good version of wkhtmltopdf to install for `report_webkit` (https://travis-ci.org/OCA/OCB/jobs/49717407), I'd be thankful.

**Comment by yvaucher** [comment]
@hbrunn https://github.com/OCA/account-financial-reporting/blob/8.0/.travis.yml#L17-18

This is the last version of wkhtmltopdf known to work correctly.

**Comment by hbrunn** [comment]
Thanks @yvaucher, I'll try with this version

**Comment by hbrunn** [comment]
aha, not we're down to one error in `openerp.addons.stock.tests.test_stock_flow: FAIL`. Alls the others seem to be caused by the fact that the scripts up to now either called the test in update mode or two times init, not all modules like this.

Could one of the warehousing people look into this?

**Comment by hbrunn** [comment]
cf. https://travis-ci.org/OCA/OCB/jobs/50941354

**Comment by hbrunn** [comment]
its green :clap:

**Comment by pedrobaeza** [comment]
Wow, what a huge task! So I assume that it can't be simplified, doesn't it?

**Comment by yvaucher** [comment]
:tada: 

:+1:

**Comment by hbrunn** [comment]
@pedrobaeza some of the partitions could be combined, but given that runtime changes with travis' load it'd suggest not to do that in order to have bigger error margins

**Comment by pedrobaeza** [comment]
Thanks for the explanation.

:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
