### PR TITLE
On module update or init always update module list (backport)

### PR DESCRIPTION
**Pull request by dreispt**
Upstream proposals:
- https://github.com/odoo/odoo/pull/9133  - accepted in principle, but rejected for stable
- https://github.com/odoo/odoo/pull/9140  - proposed for master, pending review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Yes, please!!!

:+1:

**Comment by StefanRijnhart** [comment]
Much appreciated! :+1:

**Comment by dreispt** [comment]
Please make my day :wink:

**Comment by StefanRijnhart** [comment]
With pleasure!

**Comment by dreispt** [comment]
Thanks! What's the policy to forward port OCB PRs? Should I also open a PR for 9.0?

**Comment by antespi** [comment]
Thanks @dreispt !!

**Comment by StefanRijnhart** [comment]
@dreispt Yes, please. In the ideal case, a change to OCB is also merged by Odoo into master. The submitter is strongly encouraged to propose for any later release that does not yet contain the change. That would be 9.0 in this case.

Unfortunately, there is no systematic tracking of the status of all the bugfixes in the various versions of OCB. I don't see how to do that in an efficient way with Git and Github. I don't long back to the Launchpad days, but this easier to do there where all the bugs had a single entry point (bar duplicates).

**Pull request merged**
