### PR TITLE
[FIX] MO: change required conditions on bom_id

### PR DESCRIPTION
**Pull request by rdeheele**
on mrp.production form view, bom_id field may be
not required on after draft states.
If the linked BOM is deleted, it avoids to block
the MO usage with the following message:
The following fields are invalid: Bill of Material

linked to https://github.com/odoo/odoo/issues/3417

### CODE REVIEW

**Comment by clonedagain** [comment]
:+1:

**Comment by guewen** [comment]
Needs a rebase

**Comment by rdeheele** [comment]
@guewen I think that I should close this PR because Odoo has chosen to fix it as it : e27afc13cb5d95831cb9f4a0f1fb98e70129ceed
See too: https://github.com/odoo/odoo/issues/3417

**Comment by guewen** [comment]
Right.

**Pull request closed without merging**
