### PR TITLE
[13.0] web: backport image widget zoom issues

### PR DESCRIPTION
**Pull request by chienandalu**
Backports of:

- https://github.com/odoo/odoo/commit/04af701f7658f260f81eb56f35fb64c4200b1e53 [FIX] web: Fix the zoom image stick top on search of employee.
- https://github.com/odoo/odoo/commit/7304bd20549ded71dc54072738515ea90aa9d6cd [FIX] web: fix picture glitch

Rationale in the coomits' messages

cc @Tecnativa TT42191

ping @pedrobaeza @CarlosRoca13 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Testing on runboat, I still have the problem:

Peek 24-03-2023 12-00

May it be that this special runboat doesn't reflect the PR changes, or is it that the patch is not complete?

**Comment by chienandalu** [comment]
> May it be that this special runboat doesn't reflect the PR changes

Yeah, looks like that's what's happening:

image

**Comment by pedrobaeza** [comment]
@sbidoul do you know if this is a limitation of the runboat infrastructure?

**Review by pedrobaeza — APPROVED** [review]

**Comment by chienandalu** [comment]
As tested in my local:

Peek 24-03-2023 12-14

**Comment by pedrobaeza** [comment]
Great, let's merge the patches for now.

**Pull request merged**
