### PR TITLE
[FIX] English translations can be empty and still OK

### PR DESCRIPTION
**Pull request by yajo**
If you database included some English translations, those get the translated value empty by design, given *the original purpose of empty translations was to mean the field is not yet translated*.

https://github.com/OCA/OCB/pull/710 introduced a breaking change where an empty translation *now means that you really want the field contents to disappear* in the target language.

We have to skip en_US from that POV.

Honestly I think we should completely rollback that PR. If you want an empty translation, you just have to write `" "` into it, that's enough. I guess nobody noticed this logical breakage, but I guess it's gonna produce many failures for many people that will start seeing empty things where there was English text before...

In any case I started by fixing my specific problem, but I can switch to undoing that commit if we agree on that.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Comment by hbrunn** [comment]
I did this being quite convinced this is the right thing to do, but also this week some weirdnesses popped up that I suspect have to do with this, so my plan was to analyse this next week. But you already hit the nail: Bad idea, let's revert this. Can you better push a reverting commit?
For the customer where this hurts I'll overwrite `write`/`create` to do the right thing in the null/'' case

**Comment by Yajo** [comment]
OK, given the importance I'm gonna make a direct commit reverting that one to the 8.0 branch if you don't mind. Thanks!

**Comment by Yajo** [comment]
I'm gonna fast-track this, I hope you understand. Thanks!

**Comment by yajo** [comment]
Yikes! I have no commit rights here... Well, somebody fast-track this please. Thanks!

**Comment by pedrobaeza** [comment]
Yeah, I'm doing it.

**Pull request merged**
