### PR TITLE
[FIX] add context in fiscal position creation to transmit configuration by templates

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial patch to pass context, when creating fiscal position via template.
Allow to make inheritance mechanism.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
If we only merge this in OCB and not in Odoo upstream, there will be modules that use this inheritance mechanism and work only on OCB. Not very nice...

**Comment by StefanRijnhart** [comment]
True, that is a risk. In the old days, OCB was top heavy with PRs that just passed the context everywhere but maybe it does not fit a stricter definition of compatibility. But in this case it's bordering on saying that OCB is not compatible with Odoo because it does not display the behaviour of the bug, and you have to ask where does it end?

**Comment by legalsylvain** [comment]
Hi @StefanRijnhart and @pedrobaeza Thanks for your review.

> If we only merge this in OCB and not in Odoo upstream, there will be modules that use this inheritance mechanism and work only on OCB. Not very nice...

Indeed, but I don't see any workaround. 8.0 serie is not supported anymore by Odoo SA, so I'll not propose PR against odoo/odoo/8.0 because I'm sure it will be rejected.

I set a note in the module I proposed in the 8.0 OCA repo (account-fiscal-rule)
https://github.com/OCA/account-fiscal-rule/pull/93/files#diff-414d83f20ab62c068511310913496c3bR58

For my side, I propose this work and patch *in the case it could be usefull*, but I'll migrate GRAP database for sure this year. So I'll not spend time to make it better.

I let the community accept or refuse this PR. (and the other one)

**Comment by pedrobaeza** [comment]
I'm not using 8.0 anymore, and any way I only use OCB, but the case is where to set the red line. I abstain in this case for not blocking what is obviously a blocking point for doing this, but in the same sense, people can start to propose hooks for methods with the same purpose.

**Comment by StefanRijnhart** [comment]
Agree with Pedro that it is not acceptable to implement a change in OCB to facilitate the functionality of a module in an OCA repo.

**Comment by legalsylvain** [comment]
Well, I see it as a bugfix, and I thought it was the objective of OCB. Not passing the context is an error. 
But well, no problem ! 
thanks for your reviews.

**Pull request closed without merging**
