### PR TITLE
[FIX] keep the context we got in Many2ManyDataset

### PR DESCRIPTION
**Pull request by hbrunn**
upstream: https://github.com/odoo/odoo/pull/6966

This fixed binary fields in many2many fields being downloaded on view

### CODE REVIEW

**Comment by hbrunn** [comment]
this is a followup of https://github.com/OCA/OCB/pull/140, that does the same for the Many2One dataset

**Comment by pedrobaeza** [comment]
:+1:

**Comment by legalsylvain** [comment]
:+1: LGTM.

**Comment by hbrunn** [comment]
merged in upstream

**Pull request closed without merging**
