### PR TITLE
Faster orm intersect

### PR DESCRIPTION
**Pull request by ccomb**
Backport of odoo#6594 which helps on a custom implementation.
On some unittests I gain at least 15% of the overall execution time.
The intersect() function is not used anymore, but I've kept it in place in case someone else uses it.

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by bwrsandman** [comment]
Be aware that using `set` to remove duplicates destroys the order of a list. A viable alternative is using `OrderedDict`.

Not sure if that matters in this case, just making sure it's been taken into consideration.

**Comment by gdgellatly** [comment]
The lists in this case are all unordered as they come from dict keys.

**Comment by bwrsandman** [comment]
Good to know

**Pull request merged**
