### PR TITLE
[ADD] add sequence on product attribute line

### PR DESCRIPTION
**Pull request by rdeheele**
Add a sequence field on product.attribute.line object.
Allows to order attributes on the product form.

### CODE REVIEW

**Comment by agb80** [comment]
:+1:

**Comment by gdgellatly** [comment]
Hi,

:-1: This could easily be introduced in a module and has no reference to upstream PR.

More over I don't think it does anything useful as it stands.  Runbot is not working so I can't tell for sure but in all my manual tests doing exactly this it didn't.

I've been working in product-attribute repo for some time now porting product_variant_multi functionality and reviewing the PR's.  One of the first things I did was this change and it simply doesn't work.  I have also left a note in akretions product_code PR's on that repo to check their implementation.

In my testing, just reordering the sequence does not change the order by which they are read by create_variant_ids which means just a simple change like this introduces a UI defect.  The user expects the first attribute first, the second one second which is what occurs now.  Introducing this stops that behaviour.

My question becomes then, what is the expected user benefit of this change?

e.g. 
What should happen when a user reorders the attributes on an existing template and clicks save? (btw - this will trigger create_variants as anytime attribute_line_ids is in write it is triggered).  Should the words be reordered?

What should happen when a user reorders new attribute lines on an existing template?
What should happen in both those cases for a new template?

My answer is it should be the same thing,  it should reorder the attribute values appearance order on the products.  Right now I don't think it does this at all.  Of course it would be nice if runbot was running so I could say definitively, as I could be using an outdated revision, or simply have my own code wrong, so I could be completely wrong.

**Comment by rdeheele** [comment]
Hi Graeme,

Ok, I didn't think about attribute values appearance order on the product variants because I combine it with the odoomrp-wip addon : product_variants_no_automatic_creation where I can create attribute without generate automatically the product variants.
My final expected benefit is to have an ordered list of attributes according the user preferences when he uses mrp_product_variants or/and sale_product_variants (addons coming from odoomrp-wip https://github.com/odoomrp/odoomrp-wip ) : in these addons, the user selects a product, then a list of attributes is proposed to be filled.
I don't think about these possible side effects, I think to propose an independent addon in https://github.com/OCA/product-attribute

**Comment by pedrobaeza** [comment]
Anyways, OCB doesn't allow changes to the DB layout, because it will break the compatibility Odoo <> OCB, but as a new module it seems very convenient for the use that you are mentioning, Romain.

**Pull request closed without merging**
