### PR TITLE
[FIX] round discount to one decimal

### PR DESCRIPTION
**Pull request by hbrunn**
upstream PR: https://github.com/odoo/odoo/pull/14651

### CODE REVIEW

**Review by PierreFaniel — APPROVED** [review]
@hbrunn Thanks for this!

**Review by susport — COMMENTED** [review]
OK 👍

**Comment by StefanRijnhart** [comment]
Looks good (especially the removal of ugly, duplicate code). Maybe you can convince Martin on the upstream PR with a test?

**Comment by hbrunn** [comment]
the issue itself is fixed in https://github.com/odoo/odoo/commit/d612daae719ce3da86c3e44a91a6138a1733dcc2, but the author didn't seem to find it a good idea to do away with the horrible code duplication there. Closing anyways

**Pull request closed without merging**
