### PR TITLE
[FIX] round nonstored computed float fields

### PR DESCRIPTION
**Pull request by hbrunn**
Upstream PR: https://github.com/odoo/odoo/pull/11505, also read https://github.com/odoo/odoo/pull/11441

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@hbrunn, can you point me to a place (in runbot) where I can see the problem before and after?

**Comment by hbrunn** [comment]
@pedrobaeza follow the steps for creating an expense: https://github.com/odoo/odoo/pull/11505#issue-143911674

**Comment by StefanRijnhart** [comment]
Thanks! What is the situation for new API computed float fields?

**Comment by hbrunn** [comment]
never checked that to be honest

**Comment by StefanRijnhart** [comment]
I would really like you to check that out, so that we don't run into this bug again once this particular field has been migrated to the new API.

**Comment by hbrunn** [comment]
@StefanRijnhart 61891fc

**Comment by hbrunn** [comment]
PS: the next commit deletes the pdb statement...

**Comment by StefanRijnhart** [comment]
Thanks. You could have just said that new API fields are OK because now we have a change with a test that does not apply to the change itself but it's not a perfect world is it. :+1:

**Pull request merged**
