### PR TITLE
[FIX] #3670 Don't override previous value if no journal is found

### PR DESCRIPTION
**Pull request by ccomb**
same as v7 #194

### CODE REVIEW

**Comment by pedrobaeza** [comment]
See my comment https://github.com/odoo/odoo/issues/3670#issuecomment-91308238

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
@pedrobaeza comment was replied here https://github.com/odoo/odoo/issues/3670#issuecomment-91317518

:+1:

**Comment by StefanRijnhart** [comment]
:-1: pending discussion on the issue

**Comment by StefanRijnhart** [comment]
oh, too late

**Comment by yvaucher** [comment]
@StefanRijnhart Do you want to revert ?

**Comment by StefanRijnhart** [comment]
No, @ccomb replied on the issue and I'm trusting his judgement in the matter.

**Pull request merged**
