### PR TITLE
[IMP] project: Copy value from date_deadline to date_end if date_end …

### PR DESCRIPTION
**Pull request by sergio-teruel**
…has not been modified. https://github.com/odoo/odoo/pull/8512

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Comments in upstream

**Comment by rafaelbn** [comment]
@pedrobaeza If Odoo doesn't answer this or don't accept this PR will be accepted or we must make a single module?

**Comment by pedrobaeza** [comment]
I think this can be in OCB although Odoo doesn't accept it.

**Comment by rafaelbn** [comment]
Must we wait? How long?

**Comment by pedrobaeza** [comment]
First, you need at least 2/3 persons that approve this PR. Then, wait for at least another week to see what Odoo says.

**Comment by rafaelbn** [comment]
Tested in runbot :+1: 
This is very needed for planning!

**Comment by dgzurita** [comment]
Tested in runbot :+1:

**Comment by rafaelbn** [comment]
@pedrobaeza As odoo answer in upstream ther are not going to look that PR. We have here 2 +1, if you review this PR in OCB I think it could be merged. What do you think?

**Comment by pedrobaeza** [comment]
Well, the answer is not that exactly. He has told you not to hammer him. You can be sometimes a bit insistent :wink:

**Comment by rafaelbn** [comment]
`Then, wait for at least another week to see what Odoo says.`
Week is over

**Comment by pedrobaeza** [comment]
One day more...

**Comment by rafaelbn** [comment]
@pedrobaeza after 17 days I think this PR is ready to be merged in OCB. what do you think?

**Comment by pedrobaeza** [comment]
OK, merging.

**Pull request merged**
