### PR TITLE
[8.0][FIX] Restore statusbar_colors behavior.

### PR DESCRIPTION
**Pull request by phuihock**
Related to odoo#5987

### CODE REVIEW

**Comment by yvaucher** [comment]
@phuihock Have you done a PR on odoo ? I see only the issue.

**Comment by phuihock** [comment]
@yvaucher Yup, PR #11199

**Comment by StefanRijnhart** [comment]
Looks good to me. Thanks! :+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Ok, although it's a "new" feature, it doesn't change the behaviour, only the visual part, so I think we can live with that difference.

:+1:

**Comment by StefanRijnhart** [comment]
@pedrobaeza new feature? Try grepping for statusbar_colors in Odoo 8.0 or even 9.0 ;-)
Thank you for your reviews.

**Comment by phuihock** [comment]
FWIW, there are references in the official docs from v7 to v9, though it is now superseded by `statusbar_visible` in v9. I think I wasn't the only one got confused for the "missing" feature.

Thanks for the merge.

**Pull request merged**
