### PR TITLE
[FIX] return correct amount of attachments

### PR DESCRIPTION
**Pull request by hbrunn**
when searching with a limit set (as is in list views)

Upstream PR: https://github.com/odoo/odoo/pull/7366

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Does this still applies to later versions? There were discussion about the loss of the order in the returned records, which I still consider important.

**Comment by hbrunn** [comment]
the order is preserved I think with this patch. Later versions have a similar problem, but I don't have customers to test this at the moment

**Review by pedrobaeza — APPROVED** [review]
Checked about the order preserving, so I merge.

**Pull request merged**
