### PR TITLE
[FIX] Portal dependency

### PR DESCRIPTION
**Pull request by DarioLodeiros**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, I was thinking more in odoo/odoo, not in OCA/OCB

**Comment by hbrunn** [comment]
this is not the right way to fix this anyways. Check https://github.com/OCA/OCB/issues/682

**Comment by pedrobaeza** [comment]
But if you remove or modify some data, other modules can rely on that data...

**Comment by hbrunn** [comment]
yes, and that's what I mean is the correct fix: Declare whatever of `portal`'s data is used in `project_issue`'s tests also there. Don't delete it from the portal module such as not to break other modules where the dependency exists

**Comment by StefanRijnhart** [comment]
There is a host of modules depending on portal data:
```
project_issue/data/project_issue_demo.xml:            <field name="partner_id" ref="portal.partner_demo_portal"/>
rating_project/data/project_demo.xml:            <field name="partner_id" ref="portal.demo_user0_res_partner"/>
website_crm_partner_assign/data/crm_lead_demo.xml:                  <field name="partner_assigned_id" ref="portal.partner_demo_portal"/>
website_crm_partner_assign/data/res_partner_grade_demo.xml:        <record id="portal.partner_demo_portal" model="res.partner">
website_portal_sale/data/sale_demo.xml:            <field name="partner_id" ref="portal.partner_demo_portal"/>
website_portal_sale/data/sale_demo.xml:            <field name="partner_invoice_id" ref="portal.partner_demo_portal"/>
website_portal_sale/data/sale_demo.xml:            <field name="partner_shipping_id" ref="portal.partner_demo_portal"/>
website_portal_sale/data/sale_demo.xml:            <field name="message_partner_ids" eval="[(4, ref('portal.partner_demo_portal'))]"/>
website_portal_sale/data/sale_demo.xml:            <field name="partner_id" ref="portal.partner_demo_portal"/>
website_portal_sale/data/sale_demo.xml:            <field name="partner_invoice_id" ref="portal.partner_demo_portal"/>
website_portal_sale/data/sale_demo.xml:            <field name="partner_shipping_id" ref="portal.partner_demo_portal"/>
website_portal_sale/data/sale_demo.xml:            <field name="message_partner_ids" eval="[(4, ref('portal.partner_demo_portal'))]"/>
website_project/demo/project_demo.xml:            <field name="partner_id" ref="portal.partner_demo_portal"/>
website_project/demo/project_demo.xml:            eval="[ref('project.project_project_1')], [ref('portal.partner_demo_portal')]"/>
website_project/demo/project_demo.xml:            <field name="partner_id" ref="portal.partner_demo_portal"/>
website_project/demo/project_demo.xml
```

I don't think we can get away with disabling autoinstall for the portal module in 10.0 anymore. It is a lost cause anyway because in 11.0 the portal functionality is built in to the regular apps. I suggest we revert parts of https://github.com/OCA/OCB/pull/650

**Comment by astirpe** [comment]
I agree with https://github.com/OCA/OCB/pull/684#issuecomment-353304618 to partially revert #650.
All the PRs opened on branch 10.0 of the project repository are red.

**Comment by pedrobaeza** [comment]
Partial revert in #691

**Pull request closed without merging**
