### PR TITLE
[FIX] bug #4201 proper invoice of service from delivery with multiple pickings

### PR DESCRIPTION
**Pull request by legalsylvain**
Realized by @alexis-via, Thanks to @bguillot.
See https://github.com/odoo/odoo/pull/4204 for more information.

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:

**Comment by alexis-via** [comment]
:+1:

**Comment by gurneyalex** [comment]
@legalsylvain @alexis-via Could you throw in a small automated test?

**Comment by pedrobaeza** [comment]
:+1: with the plus of the automated test.

**Comment by sylvainc** [comment]
I confirm this issue. I also confirm that this fix solved the problem :+1:

**Pull request merged**
