### PR TITLE
access gravatar in https

### PR DESCRIPTION
**Pull request by ccomb**
Backport for odoo/odoo#3042 which is still not merged after 6 months

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by eLBati** [comment]
LGTM :+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by ccomb** [comment]
It's been modified upstream to use the current scheme with `//` instead of `https://` which seems a better idea indeed.  It will probably lead to a merge conflict?  Should I do something to prevent it?

**Comment by pedrobaeza** [comment]
When the daily script will synchronize OCB from upstream, the conflict will arise. For now, @StefanRijnhart or one of his guys are taking care of solving these conflicts.

**Pull request merged**
