### PR TITLE
Use valid email addresses in tests

### PR DESCRIPTION
**Pull request by veloutin**
This is so my email validation module 
(https://github.com/OCA/partner-contact/pull/86)
doesn't break tests when installed.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But test is not also a valid domain. Why not test.com?

**Comment by pedrobaeza** [comment]
Also, your module is going to fail against official branch. Don't you think that you should handle demo data as an exception?

**Comment by veloutin** [comment]
@pedrobaeza test is a valid domain per the RFC. It is a reserved domain used for testing.
How would I go about adding an exception to demo data? Is there a way to do that without querying
ir.model.data ?

**Comment by pedrobaeza** [comment]
Hi, Vincent, I didn't know about test indication in RFC.

About skipping test, just add an exception for that specific addresses. Not elegant, but pragmatic.

**Comment by hbrunn** [comment]
:-1: no matching PR for upstream, and I generally disagree: An email validation should check for syntactically valid addresses, and not make assumptions on which TLDs exist (it's only that right now there are no one letter TLDs, they probably won't ever come, but still, it's possible). I had a hell of a time when I was the proud new owner of an .email TLD and virtually all email validations choked on it.

**Comment by pedrobaeza** [comment]
As there's no answer, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
