### PR TITLE
[FIX] Let set inactive on project stage

### PR DESCRIPTION
**Pull request by vrenaville**
Hello I have explain the issue on 
https://github.com/odoo/odoo/issues/3416

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The problem with this patch is that modifies DB layout, so it's difficult to be included here on in upstream 8.0.

I think we can handle it without this field, because you don't have to add this stage to a project, and there is a field to indicate if the stage is included in project by default.

Let's see what others say.

**Comment by StefanRijnhart** [comment]
I would have no problem with it if it was accepted in Odoo/master, but the bug has been declared invalid on the upstream project so :-1:

**Comment by dreispt** [comment]
This is best provided by an extension module.
You would be welcome to propose it to the project-service.
I suggest it to be included in the [project_stage_state](https://github.com/OCA/project-service/tree/8.0/project_stage_state) module.

**Comment by gurneyalex** [comment]
@vrenaville I agree with @dreispt that this should be done in an OCA addon. 

:-1: and closing.

**Pull request closed without merging**
