### PR TITLE
[IMP] Add index on payment_line on fkey to move_line, this key is nee…

### PR DESCRIPTION
**Pull request by yvaucher**
Upstream patch: https://github.com/odoo/odoo/pull/7261

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1:. Can you prepare the same change on OCB 8.0? A cherry-pick should apply cleanly. Odoo merges 7.0 into 8.0 periodically, so you would not need to prepare a separate PR onto Odoo 8.0.

**Comment by yvaucher** [comment]
@StefanRijnhart Sure

**Comment by yvaucher** [comment]
here we go https://github.com/OCA/OCB/pull/262

**Comment by mdietrichc2c** [comment]
:+1:

**Pull request merged**
