### PR TITLE
[IMP] Add the corresponding content type document instead the default co...

### PR DESCRIPTION
**Pull request by StefanRijnhart**
...ntent type
The content type is available for documents that have been uploaded after the document module was installed. Backport of https://github.com/odoo/odoo/pull/4294/files by El Hadji Dem. Merged in master https://github.com/odoo/odoo/commit/ae056ddc07d57fec1706cd960da7ff7ca27a7769

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
This replaces https://github.com/OCA/OCB/pull/113

**Comment by pedrobaeza** [comment]
Thanks for fixing the PR

:+1:

**Comment by lmignon** [comment]
:+1:  Thank you for the backport

**Comment by StefanRijnhart** [comment]
For the record, 6.1 port is here (and already being reviewed by @pedrobaeza and @hbrunn !) https://code.launchpad.net/~therp-nl/ocb-web/6.1-content_type_bwrsandman/+merge/248786

**Comment by hbrunn** [comment]
:+1: (can be merged if restarted tests work out)

**Pull request merged**
