### PR TITLE
[FIX] wrong mail destination address

### PR DESCRIPTION
**Pull request by hurrinico**
I create this Pull Request in order to move this: https://github.com/odoo/odoo/pull/2033/files

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by eLBati** [comment]
Fixed on odoo with https://github.com/odoo/odoo/commit/419d934143423c524fa5d5f9c6257ee4231b8502
Shall we have to fix conflicts?

**Comment by hbrunn** [comment]
Yes, just did it: https://github.com/OCA/OCB/wiki/7.0-2014-12-03

We shouldn't have merged this in the first place because the semicolon is not the right separator for mail addresses

**Comment by eLBati** [comment]
Thanks!

**Pull request merged**
