### PR TITLE
only run postinstall tests for updated modules

### PR DESCRIPTION
**Pull request by gurneyalex**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

closes #9768

### CODE REVIEW

**Comment by gurneyalex** [comment]
8.0 version of #393

upstream PR is https://github.com/odoo/odoo/pull/11378

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lepistone** [comment]
Thanks :+1:

**Comment by Garamotte** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Merging also.

Thanks.

**Pull request merged**
