### PR TITLE
 [8.0] [FIX] stock: let resupply from warehouse work

### PR DESCRIPTION
**Pull request by gurneyalex**
If you set WH B to be resupplied from WH A, then the scheduler will generate a procurement with warehouse_id = B and location_id = B.stock. Running the procurement will find the resupply rule, and this will create another procurement with warehouse_id = A and location_id = transit location.

However, without this patch, the resupply route is not part of the route_ids of warehouse A, and so the 2nd procurement goes in exception because if cannot find a rule (the search will force a rule linked to a route which is part of A.route_ids)

### CODE REVIEW

**Comment by gurneyalex** [comment]
port of odoo/odoo#7956

**Comment by pedrobaeza** [comment]
The test you have provided is failing

**Comment by gurneyalex** [comment]
@pedrobaeza yes, the presence of the JIT scheduler breaks the test. I've just pushed an updated version

**Comment by pedrobaeza** [comment]
Please squash all commits in one, but :+1:

**Comment by gurneyalex** [comment]
why squash ? These are three distinct steps in  the patch creation, following the traditional TDD pattern (red / green / refactor)

**Comment by pedrobaeza** [comment]
Well, Odoo traditionally merges all in one, and to easy the sincronization, for having the same on both parts.

**Comment by gurneyalex** [comment]
merged upstream.

**Pull request closed without merging**
