### PR TITLE
[BUG] [8.0] base: ir_sequence fix to Portgresql 10.0

### PR DESCRIPTION
**Pull request by acysos**
Description of the issue/feature this PR addresses: bug in increment_by in postgresql 10.0

Current behavior before PR: bug in sequences without gap

Desired behavior after PR is merged: solve the bug

The is code is backport from Odoo 9.0.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Did you need any adaptation of the patch or can you cherry-pick the commit directly from upstream versions? Maybe you can cherry-pick and add an extra commit with the adaptations, but you should preserve commit authorship.

**Comment by Maartincm** [comment]
I think you should keep the format expression **03d** because a relation named `ir_sequence_040` would fail because the format would end up with something like `ir_sequence_40`.
So **%(seq_id)s** should be **%(seq_id)03d** imho.
Cheers!

**Comment by rlizana** [comment]
:+1: LGTM

**Comment by pedrobaeza** [comment]
Please cherry-pick the commit for preserving author.

**Comment by pedrobaeza** [comment]
Closing as #803 preserves commit author.

**Pull request closed without merging**
