### PR TITLE
[FIX] Removes the limit of 64 characters from additional text fields added via the interface

### PR DESCRIPTION
**Pull request by LaurentBxl**
[FIX] Removes the limit of 64 characters from additional text fields added via the interface

https://bugs.launchpad.net/openobject-server/+bug/1053511

This change is the same as done in:
http://bazaar.launchpad.net/~openerp-dev/openobject-server/7.0-opw-582876-cbi/revision/4908

### CODE REVIEW

**Comment by eLBati** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
I don't think OCB 6.1 should be moved to GitHub :-1:

**Comment by LaurentBxl** [comment]
OK. I'm just confused on which repository to use as Github and LP have both fairly recent changes

**Comment by bwrsandman** [comment]
8.0 is on Github while 7.0 and lower is on Launchpad.
The recent changes to branches is due to OCB only being a fork of Odoo at this point, so their changes are here, along with the dates.

@StefanRijnhart I think we should branch master as 8.0 and remove all other branches to keep this repo clean with only 8.0 here.

**Comment by StefanRijnhart** [comment]
Done removing other branches. We will have 7.0 in some time again here.

Do we need to take special measures to keep tracking odoo/master for now when we create the ocb/8.0 branch?

**Comment by bwrsandman** [comment]
How did you track it previously?

## Merge strategy:

``` bash
cd OCB
git checkout 8.0 
git pull OCB-upstream 8.0
git pull odoo-upstream master
git push OCB-upstream 8.0
```

## Rebase strategy:

``` bash
cd OCB
git checkout 8.0-odoo
git pull odoo-upstream master
git checkout 8.0
git pull OCB-upstream 8.0
git rebase -i 8.0-odoo
git push -f OCB-upstream 8.0
```

I think you can also do some git config magic

**Comment by StefanRijnhart** [comment]
I did not configure any tracking manually, this repo was forked. Anyway, if Odoo branches 8.0 later on, will we get that branch in this repo automatically? In that case we should probably not do anything now.

**Comment by bwrsandman** [comment]
A fork won't automatically keep up to date with its source.
You need to update it yourself or with a bot.

**Pull request closed without merging**
