### PR TITLE
[7.0] Translate Error and Warning dialog titles (lp:1297525)

### PR DESCRIPTION
**Pull request by bwrsandman**
https://github.com/odoo/odoo/pull/22

Fix for https://bugs.launchpad.net/openerp-web/+bug/1297525 :

> When an except_osv or except_orm is raised in a non-english environment, the title of the Pop-up window is "OpenERP Warning" and there is no way to change that.
> 
> The same is true for "Access Denied"

Translate error messages in web and server
Add lookup `context` in `self` in translate.py's `_` function

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The problem I see with this is that translations will not be accesible from OCB, so the strings will remained untranslated until someone changes in each DB.

BTW, :+1:

**Comment by lmignon** [comment]
:+1:

**Comment by bwrsandman** [comment]
This is kind of an old patch, I hope it still works. It would be good to have a runbot so someone else can test this. :worried: 

We can always check on the runbot of https://github.com/odoo/odoo/pull/22

**Comment by gurneyalex** [comment]
@bwrsandman please rebase your branch and you'll get a runbot build :smile_cat:

**Comment by bwrsandman** [comment]
I'd like to avoid rebasing since I am using the sha in production.

Reopening the PR gets travis to restart, I am hoping so will runbot

**Comment by gurneyalex** [comment]
@bwrsandman I manually created a runbot.build record in the runbot. Should be built by the time you get at the office.

**Comment by yvaucher** [comment]
:+1: 

There is no DB on runbot? @gurneyalex

**Comment by pedrobaeza** [comment]
As this one is no valid due to the problem mentioned with translations, I close.

**Pull request closed without merging**
