### PR TITLE
[8.0][FIX][hr_holidays] Allow to overlap different types

### PR DESCRIPTION
**Pull request by yajo**
Downstreaming https://github.com/odoo/odoo/pull/11026 to OCB.

@Tecnativa

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Al least!

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by yajo** [comment]
It says `The job exceeded the maximum time limit for jobs, and has been terminated`, but no error in logs so far.

**Comment by pedrobaeza** [comment]
Let's rebuild again to see

**Review by pedrobaeza — APPROVED** [review]
Merged upstream in v10, so merging also this one

**Pull request merged**
