### PR TITLE
[UPD] crm: fill lead title & function on onchange

### PR DESCRIPTION
**Pull request by rdeheele**
fill crm.lead title & function fields on onchange_partner_id

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is there a PR or issue in upstream? Please refer it.

**Comment by rdeheele** [comment]
@pedrobaeza https://github.com/odoo/odoo/pull/5388 on Odoo

**Comment by pedrobaeza** [comment]
:+1:

**Comment by laurentmeuwly** [comment]
:+1:

**Comment by rdeheele** [comment]
added by https://github.com/OCA/OCB/commit/4a3c4713e92289ba55bcca287f77483621efee16
then I close the PR.

**Pull request closed without merging**
