### PR TITLE
11.0 [REF] .travis.yml: Enable test_crawl and exclude just hw_scanner and hw_escpos

### PR DESCRIPTION
**Pull request by moylop260**
- [x] Waiting more feedback from #736

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by moylop260** [comment]
@StefanRijnhart 
We are waiting for you too here

**Comment by StefanRijnhart** [comment]
Yes, sorry, I was ill

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by StefanRijnhart** [comment]
Strangely enough, the main branch build breaks on exactly the crawl test which was green here https://travis-ci.org/OCA/OCB/jobs/373369457

**Comment by moylop260** [comment]
@StefanRijnhart 
What is build red?

The last build of the branch 11.0 is green.

**Comment by pedrobaeza** [comment]
That's because I have restarted it and get green finally (a Travis glitch?)

**Comment by StefanRijnhart** [comment]
The applications job failed initially and after a first restart. Apparently, we needed @pedrobaeza's magic touch!

**Pull request merged**
