### PR TITLE
Optimize stock_move.setlast_tracking()

### PR DESCRIPTION
**Pull request by guewen**
When setlast_tracking is called on a large number of moves in a picking
(e.g.  when splitting moves in a picking), the time to complete grows
exponentially.  The reason is that it loops over all the moves of a
picking, even if it keeps only the last tracking.

The method now uses a search() with a limit so it doesn't need to browse
all the moves.

When testing, I created a picking with 1 move of X units that I split in X
moves of 1 unit. It took with the original method:
- X = 10: 0.8 second
- X = 100: ~11 seconds
- X = 1000: ~340 seconds

Now:
- X = 10: 0.7 second
- X = 100: ~8 seconds
- X = 1000: ~90 seconds

Proposed upstream: https://github.com/odoo/odoo/pull/2448

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Only one thing: if you force `order='tracking_id DESC',`, if model order changed, you won't get the same result as the index [-1] of the original code. This is a remote possibility, but OCB can continue for v9, v10... and nobody knows. What about this piece of code?:

```
move_ids = self.search(cr, uid, [('picking_id', '=', picking_id), ('tracking_id', '!=', False)], context=context)
tracking_move = self.browse(cr, uid, move_ids[-1], context=context)
```

Has it any impact on times?

**Comment by guewen** [comment]
@pedrobaeza the previous code was 
1. building a list of tracking ids of the moves of the picking
   
   ```
   last_track = [line.tracking_id.id for line in picking.move_lines if line.tracking_id]
   ```
2. sorting them
   
   ```
   last_track.sort()
   ```
3. Taking the last one of the sorted list, so the biggest ID
   
   ```
   last_track = last_track[-1]
   ```

It is totally the same thing than what I'm doing with the search query 'tracking_id DESC' and 'limit 1'.

**Comment by pedrobaeza** [comment]
Yeah, you're right. It's the same. I miss the sort call...

Thanks for the patch.

:+1:

**Comment by lmignon** [comment]
:+1:  LGTM

**Comment by moylop260** [comment]
FYI in our runbot this PR is red
http://odoorunbot.vauxoo.com/runbot/team/ocb-5

section log with error
openerp.modules.loading: module stock: loading test/setlast_tracking.yml
2014-09-18 09:49:21,250 25120 TEST 16799-47-7-0-oc-all openerp.tools.yaml_import: In order to check if the last tracking is set on moves, I create a picking
2014-09-18 09:49:21,438 25120 TEST 16799-47-7-0-oc-all openerp.tools.yaml_import: Creating !record {model: stock.move, id: shipment_tracking_move1}:
 with {'location_dest_id': 'stock_location_output', 'product_id': 'product_product_6', 'product_uom': 'product.product_uom_unit', 'product_qty': 10.0, 'location_id': 'location_monitor', 'picking_id': 'shipment_tracking'}
2014-09-18 09:49:21,563 25120 TEST 16799-47-7-0-oc-all openerp.tools.yaml_import: Creating !record {model: stock.move, id: shipment_tracking_move2}:
 with {'location_dest_id': 'stock_location_output', 'product_id': 'product_product_6', 'product_uom': 'product.product_uom_unit', 'product_qty': 10.0, 'location_id': 'location_monitor', 'picking_id': 'shipment_tracking'}
2014-09-18 09:49:21,694 25120 TEST 16799-47-7-0-oc-all openerp.tools.yaml_import: Then I call setlast_tracking on the moves and check if the tracking is correct
2014-09-18 09:49:21,731 25120 ERROR 16799-47-7-0-oc-all openerp.tools.yaml_import: AssertionError in Python code : The tracking must be a new one

travis is green but only is installing base module.

**Comment by guewen** [comment]
It has been merged in 7.0 so it is not anymore useful to merge it here.

**Pull request closed without merging**
