### PR TITLE
[FIX] due date computation computation errors

### PR DESCRIPTION
**Pull request by damdam-s**
see https://github.com/odoo/odoo/pull/10458 for more information

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Setting to WIP pending upstream discussion

**Comment by gurneyalex** [comment]
:+1:

**Comment by njeudy** [comment]
:+1: 

I manage to use a module to do that, this PR is really better

Note: how to restart test ?

**Comment by gurneyalex** [comment]
@StefanRijnhart do you have an opinion on this given the current discussion on upstream PR?

**Comment by gurneyalex** [comment]
@njeudy I manually restarted the runbot build which is now green.

**Comment by StefanRijnhart** [comment]
I have to say, the labels in the interface are pretty ambiguous and I don't like it either when OCB changes standard behaviour of Odoo if the old behaviour could be considered right according to some interpretation. I'll abstain for now.

**Comment by gurneyalex** [comment]
closed by upstream :cry:

**Comment by pedrobaeza** [comment]
I don't get what do you want to get. Can you explain it to me to understand it?

**Comment by gurneyalex** [comment]
@pedrobaeza I want to have an invoice payment term 2 month end of month (invoice date 23 march, due date 31st may)

**Comment by gurneyalex** [comment]
moved this code to https://github.com/OCA/account-invoicing/pull/141

**Comment by gurneyalex** [comment]
@njeudi the PR above was merged

**Pull request closed without merging**
