### PR TITLE
[FIX][8.0] Membership dates on children propagation

### PR DESCRIPTION
**Pull request by antespi**
See https://github.com/odoo/odoo/pull/8207

### CODE REVIEW

**Comment by rafaelbn** [comment]
I cannot test this FIX, in runbot I get this error:

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3113668-313-b4e61b/openerp/http.py", line 537, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3113668-313-b4e61b/openerp/http.py", line 1413, in _dispatch_nodb
>     func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
>   File "/srv/openerp/instances/openerp-oca-runbot/sandbox/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
>     raise NotFound()
> NotFound: 404: Not Found

**Comment by pedrobaeza** [comment]
As explained on upstream, :+1:

**Comment by pedrobaeza** [comment]
I have restarted Travis to see if the error is still there (although it's probably, because OCB is synchronized on nights).

**Comment by rafaelbn** [comment]
Tested in runbot, bug fixed! :+1:

**Comment by yvaucher** [comment]
This was merged upstream at https://github.com/odoo/odoo/commit/f310a82a20273835c21151b4f83bf7275f5e58f2 thus I close this

**Comment by yvaucher** [comment]
Thanks @antespi

**Pull request closed without merging**
