### PR TITLE
[7.0] When first generating user groups xml, use SUPERUSER's context

### PR DESCRIPTION
**Pull request by bwrsandman**
Odoo PR: https://github.com/odoo/odoo/pull/3921

Fixes English User groups

Currently, on non-english systems, groups on the user's form have English names.

This patch allows translation at install time according to the superuser's context at install time

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Seems a good solution, although depending on Superuser language.

:+1:

**Comment by bwrsandman** [comment]
> depending on Superuser language

This is due to the design of the form view, I am not going to change all that.

Since the superuser is usually the one assigning user permissions, I think we can accept it. ;)

**Comment by pedrobaeza** [comment]
Yeah, of course! And it's better than current :)

**Comment by guewen** [comment]
:+1:

**Pull request merged**
