### PR TITLE
[FIX] don't recompute old fields if recompute=False

### PR DESCRIPTION
**Pull request by hbrunn**
This changes make `_write()` behave like `_create()` in respect of `context['recompute']` and `env.recompute`: https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L4266

Upstream PR: https://github.com/odoo/odoo/pull/6626

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks

:+1:

**Comment by gurneyalex** [comment]
It looks fine to me. 

Can you explain what the gain of this change is, and if you see edge cases where it could introduce issues? I'm wary of such updates especially following the issues that were faced following the change last february in upstream 8.0...

**Comment by hbrunn** [comment]
@gurneyalex performance. If you write on a recordset, you're currently at o(n^2) as soon as old style function fields are involved, because the triggers are called for every [1..n] when writing record n.

**Comment by StefanRijnhart** [comment]
:+1:. I found the combination of querying both self.env and the context key suspicious when treating old style fields, but this seems harmless and is consistent with how they are always checked together in other pieces of the core code.

**Comment by gurneyalex** [comment]
hbrunn: thanks. 

:+1: from me

**Comment by lmignon** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1: but needs a rebase

**Comment by mdietrichc2c** [comment]
:+1: on this, mostly for consistency: I had an issue on the `write` part, with a rollbacked new object still having its `recompute_old` field in the environment.
This PR fixes this issue, but it does need a rebase.

**Comment by lepistone** [comment]
The code affected by this has changed. @mdietrichc2c made two updated PRs: https://github.com/OCA/OCB/pull/342 and
https://github.com/odoo/odoo/pull/8919.

**Pull request closed without merging**
