### PR TITLE
[9.0][FIX] update so line on analytical line when changing account_id

### PR DESCRIPTION
**Pull request by robinkeunen**
**before** 
On `account.analytical.line`
- when updating the `account_id` on an analytical line, `so_line` is not updated
- it leads to incorrect `qty_delivered` on linked sale order

**after**

- if `account_id` is in the change set, so_line is set to false
- then, qty_delivered is correctly computed 
   - on previously linked sale order
   - on newly linked sale_order

**Steps to reproduce:**

- create `sale.order` and click `confirm sale`
- click on created analytical account _SO001_ and tick 'tasks'. A new project _SO001_ is created.
- create a task _dev 1_ on the project and log 1 hour.

-> Sale order indicates `qty_delivered == 1`

Now, go back to logged line on the task _dev 1_ and change the account to any other.

-> Sale order still indicates `qty_delivered == 1` while it should indicate 0

**Use Case**

We invoice clients based on time spent on tasks. Sometime, we give free development hours to client. We then log our timesheets on the account "Client X - gift".

We don't want that time to be invoiced.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is this a problem? Please include steps to reproduce the problem in a user case.

**Comment by robinkeunen** [comment]
Here you go, @pedrobaeza, thanks for the comment.

**Steps to reproduce:**

- create `sale.order` and click `confirm sale`
- click on created analytical account _SO001_ and tick 'tasks'. A new project _SO001_ is created.
- create a task _dev 1_ on the project and log 1 hour.

-> Sale order indicates `qty_delivered == 1`

Now, go back to logged line on the task _dev 1_ and change the account to any other.

-> Sale order still indicates `qty_delivered == 1` while it should indicate 0

**Use Case**

We invoice clients based on time spent on tasks. Sometime, we give free development hours to client. We then log our timesheets on the account "Client X - gift".

We don't want that time to be invoiced.

**Comment by pedrobaeza** [comment]
I see this as a change of behavior based on your use case, not a bugfix, and thus, you must put this change in a custom module instead of here in OCB. ORM inheritance should allow you to do it overriding `_get_sale_order_line`.

Closing due to this reason.

**Comment by robinkeunen** [comment]
Hi Pedro. I don't think this is a change of behavior. The tasks' timesheet in the standard module allow you to log on several analytical account. If you do, your invoicing ends up being incorrect.

**Comment by pedrobaeza** [comment]
I think so, so if any other PSC considers this correct, we can reopen, but as said, this is something that you can easily do in a module, so there's no need of "fixing" this here.

**Comment by robinkeunen** [comment]
Ok no worries. Have a good week.

**Pull request closed without merging**
