### PR TITLE
[BCP] [IMP] base: use new filter_ext parameter

### PR DESCRIPTION
**Pull request by florentx**
Backport of https://github.com/OCA/OCB/commit/933c4450c40138452a4816428bc3d3c2d2d451e2

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This backport is not valid, as it modifies the signature of methods, sorry.

**Comment by florentx** [comment]
@pedrobaeza  it's not a method, it's the signature of utility function `openerp.tools.misc.file_open`.
It does not bring any compat issue or regression.

The purpose of the backport is to make assetsbundle safer, and close a security hole.

**Comment by pedrobaeza** [comment]
Yes, that's a method, and this will create an incompatibility of modules using such parameter between OCB with this patch and vanilla Odoo. That's not allowed in OCB.

**Comment by gurneyalex** [comment]
hello @pedrobaeza, the patch comes from Odoo

**Comment by simahawk** [comment]
also, the change is compatible as it adds another kw arg that has its own default.

**Comment by pedrobaeza** [comment]
I know, but in another version, not this one. Any change in signatures may lead to incompatibilities.

**Comment by pedrobaeza** [comment]
I don't agree in introducing such changes, and more in such older versions.

**Comment by pedrobaeza** [comment]
Let me expand my comment about incompatibility: imagine you are an Odoo module developer. You look at OCB, and check that the method `file_open` in misc has the kwarg `filter_ext`, and you use it in your module for any purpose. When using such module in vanilla Odoo, you will have an error because such keyword argument doesn't exist there! That's the incompatibility I'm talking about.

**Comment by simahawk** [comment]
@pedrobaeza I see your point but if you use OCB on non officially maintained versions it's very unlikely that you move back to official Odoo. And if you do it and you coded something specific to OCB (which you should be aware of) well, you'll have to fix your own stuff. Especially here that we are talking about low level utils and not models or other high level api.

Just my $0.02 of course :wink:

**Comment by pedrobaeza** [comment]
It's not low level utility. You can use it in your modules and they are not internal methods. You can find any developer submitting to OCA such incompatible module. Please don't do this and start a risky precedent.

**Review by pedrobaeza — APPROVED** [review]
Let's merge it for the sake of security

**Comment by florentx** [comment]
In the meantime, I've prepared a smaller patch, which should not bring any red alert anymore.

It's functionally the same feature, even if it diverges from the solution retained for 13.0 by Odoo
(13: https://github.com/odoo/odoo/commit/35565aa1b4995ac841ff2e6558858fe00b9d93c4)

**Comment by pedrobaeza** [comment]
Thanks:

/ocabot merge nobump

**Pull request closed without merging**
