### PR TITLE
[IMP] add `confirmed_sales_count` field to product 

### PR DESCRIPTION
**Pull request by simahawk**
Add a function field `confirmed_sales_count` to product for:
- knowing how much time has been sold (from the product backend view)
- show  "best sellers" in your shop (this listing is not part of this PR though)

### CODE REVIEW

**Comment by eLBati** [comment]
As reference: https://github.com/OCA/OCB/pull/255#issuecomment-113069203

**Comment by StefanRijnhart** [comment]
Hi @simahawk, your change looks like a functional extension. The policy of OCB is to allow bugfixes only. You could try this onto Odoo/master, but even they have a policy to keep out any functional extension that could easily be put in your own module.
So :-1: for this one.

**Comment by pedrobaeza** [comment]
You can still propose this as a new module.

**Comment by simahawk** [comment]
@pedrobaeza tnx for the hint :) Should I propose the new module to be included into https://github.com/OCA/website?

**Comment by pedrobaeza** [comment]
Well, this is something more of sale-workflow repo.

**Comment by simahawk** [comment]
I can go with that, no problem ;) tnx

**Pull request closed without merging**
