### PR TITLE
[FIX] Removed website from website_image controller to prevent lang redirect

### PR DESCRIPTION
**Pull request by PCatinean**
Upstream PR: https://github.com/odoo/odoo/pull/8515

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks! Setting to WIP seeing the discussion and modification on the upstream PR.

**Comment by PCatinean** [comment]
Fix merged upstream with a more conservative approach of the form multilang=False which achieves the same purpose

**Pull request closed without merging**
