### PR TITLE
[FIX] Translate fields not included in _columns, such as computed fields

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Upstream PR: https://github.com/odoo/odoo/pull/9081

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why the Travis error?

**Comment by StefanRijnhart** [comment]
@pedrobaeza Random Travis glitch. Got green after a rebuild.

**Comment by pedrobaeza** [comment]
Uhm, curious

:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by simahawk** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
