### PR TITLE
[FIX] encode python ldap's output as utf8

### PR DESCRIPTION
**Pull request by hbrunn**
Upstream PR: https://github.com/odoo/odoo/pull/12745

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash the commits, but :+1:

**Comment by NL66278** [comment]
:+1:  LGTM

**Comment by StefanRijnhart** [comment]
Will you squash the commits?

**Comment by hbrunn** [comment]
@StefanRijnhart with the squash-foo on github, I thought that's not necessary any more, but it seems to be turned off for this repo, which is a good thing imho. Also sorry @pedrobaeza for not picking up your comment in the first place, this one slipped through

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Pull request merged**
