### PR TITLE
9.0 [REF] .travis.yml: Using new template from MQT

### PR DESCRIPTION
**Pull request by moylop260**
Continuation of https://github.com/OCA/OCB/pull/730
@StefanRijnhart @mreficent

Feedback here please.

- [x] Active test_crawl
- [ ] Waiting @StefanRijnhart feedback

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
If test_crawl fails, let's find before which is the cause. Then, we can see if we can fix that or should be excluded.

**Comment by moylop260** [comment]
@mreficent 
I got it
I'm agree with you.

Do you have another feedback?

**Review by MiquelRForgeFlow — APPROVED** [review]
Well, there isn't any error. Will you port this test_crawl commit to v10 and v11?

**Comment by moylop260** [comment]
Yes, I will port it

But before, I need the @StefanRijnhart feedback and someone merge it this one...

**Comment by moylop260** [comment]
@mreficent Do you have other feedback different to `test_crawl`?
Your commented something about give me your feedback

**Comment by MiquelRForgeFlow** [comment]
Please rebase 😏

**Comment by moylop260** [comment]
I authorize to merger use "Squash and merge" button then I don't need rebase it

**Comment by MiquelRForgeFlow** [comment]
It's preferable "rebase and merge". With "squash and merge" may have conflicts in this case.

**Review by pedrobaeza — APPROVED** [review]

**Comment by moylop260** [comment]
ping @StefanRijnhart

**Review by StefanRijnhart — APPROVED** [review]
Great, thanks!

**Pull request merged**
