### PR TITLE
[FIX] digits precision on sale/th_weight

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by Garamotte** [comment]
LGTM, but all OCB PR must be proposed upstream.

**Comment by mileo** [comment]
@sylvain-garancher https://github.com/odoo/odoo/pull/9932

**Comment by rvalyi** [comment]
:+1:  the Stock Weight is defined in the product module so there is no dependency issue.

**Comment by Garamotte** [comment]
:+1:

**Comment by rvalyi** [comment]
we got 5 days, right? Merging...

**Comment by mileo** [comment]
Already merged at 16dbef4a1326f27023e7c29b1b9c9eb75bf5ca6b

**Comment by rvalyi** [comment]
@mileo gahh double KO... This is so rare they fix these bugs that I didn't even look again when I merged.

@StefanRijnhart what is the preferred way to fix that: I committed the patch but it was fixed meanwhile on upstream during the daily synchronization window. What do you prefer:

1) a revert PR now?
2) dealing with the conflict (will that create a conflict?)
3) a brute force (with push -f ) revert on OCB branch directly?

cc @pedrobaeza

**Comment by pedrobaeza** [comment]
We have to wait if there's any conflict when synchronizing with upstream, and solve it in that case.

**Comment by StefanRijnhart** [comment]
If the change was identical as in this case, having a merge on both sides is no problem at all. With in-merge changes on the odoo side, we get a simple conflict that can be resolved by taking the Odoo version. Thanks @mileo for the fix!

**Pull request merged**
