### PR TITLE
.travis.yml: Make Travis to work

### PR DESCRIPTION
**Pull request by pedrobaeza**
cc @Tecnativa

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Looks like Travis is working the way it should, just the query count that is slightly off (maybe due to a normal OCB specific patch?) and one bug in a localization. Do you need help with this?

**Comment by pedrobaeza** [comment]
I let it abandoned as I didn't have a guess what was happening. If you have the clue, please resume it and tell me what to do.

**Comment by rafaelbn** [comment]
Should we maintain this opened?

**Comment by yajo** [comment]
I rebased to see if it works, it was quite outdated.

**Comment by rafaelbn** [comment]
Should we close this one @pedrobaeza ?

**Comment by pedrobaeza** [comment]
Closing as no success for now.

**Pull request closed without merging**
