### PR TITLE
purchase: issue a write call on warehouses at install

### PR DESCRIPTION
**Pull request by gurneyalex**
this will force the creation of the Buy rule
closes #4853

### CODE REVIEW

**Comment by gurneyalex** [comment]
This is a port of https://github.com/odoo/odoo/pull/4901 to OCB

I did not think it was necessary to prune out the 2 commits which have not yet been merged from odoo 8.0 to OCB, but I can do so if people think it's better.

**Comment by gurneyalex** [comment]
@lepistone and @pedrobaeza made a positive review on the odoo/odoo#4901 PR (and maybe they would be willing to approve it on OCB too :-) )

**Comment by pedrobaeza** [comment]
Yeah, you have my :+1: also here.

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1: 
It seems those commit are in OCB now. not sure what will be the result on merge.

**Comment by gurneyalex** [comment]
@yvaucher git is smart enough to handle this.

**Comment by lepistone** [comment]
of course I :+1: this one as well

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by rafaelbn** [comment]
Hi, it looks thie PR can be merged, isn't it?

**Pull request merged**
