### PR TITLE
[REF] .travis.yml: Patch test_crawl in order to increase timeout

### PR DESCRIPTION
**Pull request by moylop260**
* Fix https://github.com/OCA/OCB/issues/667
NOTE: This is a flaky error then we need to rebuild the APPLICATIONS travis build in order to check if is reproduced again.

### CODE REVIEW

**Comment by moylop260** [comment]
@StefanRijnhart @mreficent 
This issue is a flaky error then is too complex to reproduce it then is complicated fix it.

I have created this change in order to re-build many times the travis build of `applications`

NOTE: If we disable it we don't have more false red because flaky errors for this case because the tests to open a url should be  phantomjs ones instead.

What do you think?

**Review by pedrobaeza — APPROVED** [review]

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
Let's wait some time please, I want to analyze the error with detail.

**Comment by moylop260** [comment]
@mreficent 
FYI I have created more details from the original issue:
 - https://github.com/OCA/OCB/issues/667

You can reproduce it reducing the timeout from the test_crawl.

I have created an asciinema for you reducing timeout from test_crawl (Note: You can pause and copy the code of the video):
 - [asciinema_test_crawl](https://asciinema.org/a/179738)

**Comment by moylop260** [comment]
Other important information
1. I have rebuilt the `applications` travis build 4 times and all the result was green.
2. The travis machine are low resources then spent more time for an asynchronous process like as open_url and wait N seconds...
3. Comparing the result of the log of runbot.odoo.com for 11.0 instance. Looking for the word `test_crawl: test` and seeing a line above:

| Runbot | Travis |
|--------|--------|
| screen shot 2018-05-04 at 08 42 53   | screen shot 2018-05-04 at 08 39 08 |
| [log](http://runbot12.odoo.com/runbot/static/build/325551-11-0-mail-opw-1837894-nle-2b0d68/logs/job_20_test_all.txt) `2018-05-04 12:26:57,415 19071 INFO 325551-11-0-mail-opw-1837894-nle-2b0d68-all odoo.addons.website.tests.test_crawl: public crawled 93 urls in 24.57s 11761 queries, 0.264s 126.46q per request,` | [log](https://travis-ci.org/OCA/OCB/jobs/374567758#L6048) `2018-05-04 13:22:19,521 5724 INFO openerp_test odoo.addons.website.tests.test_crawl: public crawled 63 urls in 40.87s 7672 queries, 0.649s 121.78q per request,` |
| Faster running 93 urls in 24.57s | Slower running 63 urls in 40.87s |
| 0.26s/url | 0.64s/url |

Travis is running in the double of the time with 20% less queries than runbot.
It means that travis is **3x slowest**.
That is the reason that this patch is working fine for travis.

**Review by StefanRijnhart — APPROVED** [review]
Great work!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
