### PR TITLE
[IMP] <crm_claim> Make deadline visible

### PR DESCRIPTION
**Pull request by oihane**
As suggested in https://github.com/OCA/crm/pull/33

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please make the upstream PR in Odoo

**Comment by oihane** [comment]
It's already done in https://github.com/odoo/odoo/pull/7788

**Comment by pedrobaeza** [comment]
OK, it's done in https://github.com/odoo/odoo/pull/7788

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
This one counts with 2 approvals in upstream and it's very straight-forward, so I merge.

**Pull request merged**
