### PR TITLE
[FIX] write product_qty and product_uos_qty through ORM, thereby respecting decimal precision

### PR DESCRIPTION
**Pull request by pedrobaeza**
Porting failed merge from lp@gh migration: http://bazaar.launchpad.net/~ocb/ocb-addons/7.0/revision/9959
fixes https://launchpad.net/bugs/1268594

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! Can you refer the upstream pull requests/issues in the description?

**Comment by StefanRijnhart** [comment]
Or rather, as I believe this is a foreport of a failed merge in the bzr2github process, a reference to the Launchpad issue?
[edit] Answered my own question in the pull description.[/edit]
[edit2] Need to read branch name :zzz: [/edit2]

**Comment by StefanRijnhart** [comment]
Verified the diff against launchpad MP :+1:

**Comment by pedrobaeza** [comment]
Hi, Stefan, what description do you mean?

**Comment by StefanRijnhart** [comment]
Pedro, I did not notice the meaningful name of the branch, and I requested references to the launchpad OCB commit and the launchpad issue. I put them in the description of this pull request  in a more verbose way myself when I finally noticed them.

**Pull request merged**
