### PR TITLE
Remove superfluous bracket for analytic account domain

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is a copy of https://github.com/odoo/odoo/pull/3714 .

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

Has this been proposed to upstream?

**Comment by mdietrichc2c** [comment]
@pedrobaeza yes, in https://github.com/odoo/odoo/pull/3714 . Or do you mean in 8.0?

**Comment by nbessi** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
