### PR TITLE
Fixes #3698 - CSS subtotal_footer width

### PR DESCRIPTION
**Pull request by yvaucher**
Odoo PR: https://github.com/odoo/odoo/pull/3948

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Any opened issue?

:+1:

**Comment by yvaucher** [comment]
Issue is opened and linked on odoo and is in commit message :smile: 
https://github.com/odoo/odoo/pull/3948

**Comment by jgrandguillaume** [comment]
:+1:

**Pull request merged**
