### PR TITLE
[IMP] osv.fields: Link all ids in one query for many2many ....

### PR DESCRIPTION
**Pull request by lmignon**
Description of the issue/feature this PR addresses:

Without this change, a -u all on a database with more than 13000 users takes more than 10 hours
With this change: 1h30

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Wow, this is a huge change to be done for all fields, and at least I see a problem: an INSERT with a lot of values is not more efficient than several insert sql. Raphael Collet faced this when implementing batch create. Are you aware of this?

**Comment by lmignon** [comment]
@pedrobaeza That's the way it's now implemented in Odoo 12 https://github.com/odoo/odoo/blob/12.0/odoo/fields.py#L2786.
The problem here is not the insert but the `select ... unset .. except`

**Comment by lmignon** [comment]
Travis is red, I've to check what's wrong with this change.

**Comment by sbidoul** [comment]
@lmignon postgres version too old, does not have ON CONFLICT.

**Comment by lmignon** [comment]
Indeed, I'll upgrade to pg 9.5... (at least to tests that this change doesn't break odoo)

**Comment by lmignon** [comment]
superseded by #819 since the source is not based on OCB and it's therefore not possible to modify the '.travis.yml' file into the source.

**Pull request closed without merging**
