### PR TITLE
[FIX] website_slides: Add fetch timeout

### PR DESCRIPTION
**Pull request by yajo**
This makes you actually able to install the module with demo data and unplugged from network. Otherwise, it's impossible.

This is a forward port of https://github.com/OCA/website/pull/527.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
Does this need forward porting to later releases?

**Comment by pedrobaeza** [comment]
Yes!

**Comment by pedrobaeza** [comment]
We are waiting if Odoo accepts it and forward-port according their process.

**Review by rafaelbn — APPROVED** [review]

**Pull request closed without merging**
