### PR TITLE
Add readonly=True on related field, to avoid access rights issues

### PR DESCRIPTION
**Pull request by alexis-via**
Here is the related PR on official odoo branch, with the detailed explainations about the scenario of the bug: https://github.com/odoo/odoo/pull/10587

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by Cedric-Pigeon** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Pull request merged**
