### PR TITLE
[8.0] Fix: 'reply_to' is missing in Message Dictionary

### PR DESCRIPTION
**Pull request by andreinl**
Description of the issue/feature this PR addresses:
'reply_to' is missing in Message Dictionary. It should be in the dictionary if an email has reply-to field.

Current behavior before PR:
Message dictionary has no 'reply_to' key

Desired behavior after PR is merged:
'reply_to' should be in the dictionary

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You need to make the same PR to upstream Odoo? Did you? Do you have the link?

**Comment by andreinl** [comment]
What is upstream Odoo? 10 or 8.0? I don't have any other links.

**Comment by pedrobaeza** [comment]
odoo/odoo 8.0

**Comment by andreinl** [comment]
Can you point me to some document where it is written how to make a PR to upstream Odoo? I know it's a dumb question, but I never contributed to core Odoo code.

**Comment by pedrobaeza** [comment]
Well, the procedure is the same: make a PR there...

**Comment by andreinl** [comment]
You mean official Odoo repository? I always use OCA version... If you think it makes sense I can make a PR on their version also. I never thought about it.

**Comment by pedrobaeza** [comment]
It's a requirement of OCB to propose the same to upstream Odoo to see if they fix it there instead of here.

**Comment by pedrobaeza** [comment]
The problem is that you're using the same branch for both PRs, and that can't be. Please remove here the CLA commit (which is only for Odoo), and start other branch forking odoo/odoo, and cherry-picking the involved commit.

**Comment by andreinl** [comment]
Ok, thank you Pedro, I will do it in next days. Internet connection here prevent me from doing this. Sorry. Will remove CLA immediately.

**Comment by andreinl** [comment]
As it was expected Odoo rejected my fix. Explanation is here https://github.com/odoo/odoo/pull/17544#issuecomment-307770564. Do I need to make a new PR request to OCA branch?

**Comment by pedrobaeza** [comment]
They don't reject it. They simply redirect it to master instead. The question is: is this an stand-alone patch or it will make that some addons will be compatible with OCB but not with vanilla Odoo?

**Comment by andreinl** [comment]
This will make Message Dictionary contain more information. I don't yet had enough time to investigate how difficult it will be to have the second part of the problem to be resolved, I mean create an addon that will write 'reply_to' in the 'email_from' field when creating a lead from email and use the right partner_id. Seems like just 10 lines of code, but I should test it first and if this can be interesting for OCA I will submit it also.
P.S. Redirecting to master is like rejecting for me, because I'm using v. 8.0, not 10+.

**Comment by pedrobaeza** [comment]
I'm not sure if this should be accepted according OCB rules. What do you think, @StefanRijnhart @hbrunn ?

**Comment by StefanRijnhart** [comment]
There is no reproduceable bug to fix with just this code, although the author's use case of creating leads with the email from the reply-to header is buried in the branch history. It would be interesting to have a change that consistently honours the correct usage of the reply-to header in all of the core (but what that is might be up for debate).

@andreinl, maybe work on this feature and propose to the Odoo master branch as suggested on the upstream PR? Certainly once it is accepted in master we could consider your backport of that onto 8.0 here.

**Comment by StefanRijnhart** [comment]
Closing because there is no bug and it's not a backport as per earlier discussion. If anything changes in this respect, please reopen!

**Pull request closed without merging**
