### PR TITLE
Ignore canceled order lines

### PR DESCRIPTION
**Pull request by gurneyalex**
port of odoo/odoo#6036 to OCB

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

I'm 100% committed to this change if and only if this one is accepted: https://github.com/odoo/odoo/pull/6064

Thanks a lot,

Regards,

Joël

**Comment by pedrobaeza** [comment]
Well, I will say even more. We cannot base for the moment any development (like _sale_amendment_ module) only on OCB features, because that means that we are virtually making a fork.

That will have to be the last resort.

**Comment by sebastienbeau** [comment]
This modules are really really a must to have! If it's not merge in odoo, I will be agree to merge it here if it's merge for 9. Even if we have to diverge during v8 this modules really really worth the risk.

**Comment by yvaucher** [comment]
I close this as it was accepted in odoo and pull in OCB at https://github.com/OCA/OCB/commit/3a314780c020439851e516c9221febc22fbf69c6

**Pull request closed without merging**
