### PR TITLE
fix #4839: propagate owner to chained moves

### PR DESCRIPTION
**Pull request by lepistone**
also proposed upstream as odoo/odoo#4840

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can simplify this way:

```
restrict_partner_id': procurement.move_dest_id.restrict_partner_id,
```

Because v8 propagate False value in case of empty recordset.

**Comment by guewen** [comment]
@pedrobaeza @lepistone 
The new API will propagate an empty recordset and not False so you can chain empty recordsets together. That's a detail because anyway the ORM will treat it like a False. By cons, AFAIK, you can't use a recordset when you pass a dict to create or write, so you should write:

```
'restrict_partner_id': procurement.move_dest_id.restrict_partner_id.id
```

(and there it will be a False or an integer)

**Comment by pedrobaeza** [comment]
That's what I said, @guewen, but less verbose :wink:

**Comment by guewen** [comment]
@pedrobaeza Absolutely ;-)

Can you just confirm (or not) that we must use `.id`?

**Comment by yvaucher** [comment]
It seems base proposal is not using `.id` was it really working?

**Comment by lepistone** [comment]
Ah yes @guewen, I forgot the `.id`, I'm adding it as you and @pedrobaeza suggest.

~~Still, I'm very surprised: I tested this manually, and it did fix the problem without crashing. It's used in a `create`.~~

~~Who knows!~~

**Comment by lepistone** [comment]
fixed

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
Thanks :+1:

**Comment by lepistone** [comment]
I stroke through a remark of mine which doesn't make sense. What I did test had a `.id` and then somehow I managed to delete it.

**Pull request merged**
