### PR TITLE
prevent double clicking on statusbar widget

### PR DESCRIPTION
**Pull request by gurneyalex**
Improvements over #528, includes improvements by @aab-odoo and @nim-odoo from https://github.com/odoo-dev/odoo/commit/dd1557531b38bf6d98576ce3e922486311b97e7f 

Should that branch be merged in odoo/odoo, this PR will prevent a conflict in nightly merge script of OCB.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to just revert? I think the conflict will still be with this.

**Comment by gurneyalex** [comment]
IDK. 

@hbrunn @StefanRijnhart do you have an opinion on this?

**Comment by gurneyalex** [comment]
a slightly different version was just merged; I'm pushing a revert of #528

**Comment by gurneyalex** [comment]
revert is in a87ee7b35cb100f4824ceaaa5668bfb7005c8171

**Comment by StefanRijnhart** [comment]
Thanks for the followup!

**Pull request closed without merging**
