### PR TITLE
[IMP] website_sale: controllers improvements

### PR DESCRIPTION
**Pull request by simahawk**
A bunch of improvements on the `website_sale` module controllers.
Currently it's a mess: you have everything in one huge file (main.py) and it's difficult to override/customize just small parts.

This PR does:
- refactor / organize controllers based on their area (product, shop, checkout, payment, etc)
- splits utilities method to `utils.py` and common methods into `mixin.py`
- checkout: add validation for fields. It really sucks that you can enter whatever value you want. If available, some external python libs will be used for improving validation (see `utils.py`)
- add `website_featured` field to product to be able to give priority to a product in product listing (like when you promote a product on the homepage). If you don't use it, nothing changes in current behavior

According to the refactor above, these modules have been updated too: 
- website_sale_event
- website_sale_options

### CODE REVIEW

**Comment by eLBati** [comment]
I did not investigate change goodness, but I think such a big change would increase the chance to get conflicts while merging from upstream.
Maybe you could just add punctual fixes without changing file structure?

**Comment by eLBati** [comment]
Also, it would be better to create a PR to https://github.com/odoo/odoo/ before OCB

**Comment by StefanRijnhart** [comment]
Hi @simahawk, your change looks like a big refactoring. The policy of OCB is to allow bugfixes only. If there are particular bugs that this change fixes, please file new PRs for each atomic change.
If this is a general improvement, you could try this onto Odoo/master.
So :-1: for this one.

**Comment by pedrobaeza** [comment]
Closing as conflicting.

**Pull request closed without merging**
