### PR TITLE
[FIX] sale_service: Allow a project user to close a task which has assigned. Fixes odoo/odoo#9286

### PR DESCRIPTION
**Pull request by pedrobaeza**
Upstream PR: https://github.com/odoo/odoo/pull/9352
Upstream issue: https://github.com/odoo/odoo/issues/9286

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @rafaelbn

**Comment by rafaelbn** [comment]
:+1: for me this is an issue and we must fix this. Maybe @dreispt would like to give an opinion.

**Comment by dreispt** [comment]
:+1:

**Comment by rafaelbn** [comment]
@dreispt could you comment https://github.com/odoo/odoo/pull/9352, maybe we have this upstream fixed, difficult but...

**Comment by pedrobaeza** [comment]
It has been merged upstream in https://github.com/odoo/odoo/commit/0ea130424d51c12ad6f922fc56e8a4dbd92b3b83, so I close.

**Pull request closed without merging**
