### PR TITLE
[FIX] sale: Respect round globally on sales orders

### PR DESCRIPTION
**Pull request by carlosdauden**
Before this commit, all results are rounded at line level, so there's no
possibility of getting the total globally rounded. This changes 2 things:

* The compute method, allowing to get the unrounded amounts.
* The field definition, for avoiding the rounding when saving data although
  the computation was done without rounding.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@StefanRijnhart @hbrunn I ask for your opinion here: as revealed on upstream PR: https://github.com/odoo/odoo/pull/14770, changing the type from `Monetary` to `Float` can break extensions that adds a related field to these fields. That fields have very restricted use:

* `price_total` only triggers the sales order amount total compute method.
* `price_tax` is used for summing up the order taxes total.

The alternative to patch this would be even worst: develop a module that creates alternative fields without rounding, and totally overwriting the compute method for using these fields, breaking other extensions that changes this computation.

Should we merge this, as it's very improbable that there's a related field of these 2 fields (we can even restrict it to only one if needed)?

**Comment by mart-e** [comment]
You also can try with
```diff
diff --git a/addons/sale/sale.py b/addons/sale/sale.py
index a1ebe31b51e..34ea83d042c 100644
--- a/addons/sale/sale.py
+++ b/addons/sale/sale.py
@@ -28,8 +28,16 @@ class SaleOrder(models.Model):
         for order in self:
             amount_untaxed = amount_tax = 0.0
             for line in order.order_line:
-                amount_untaxed += line.price_subtotal
-                amount_tax += line.price_tax
+                price = line.price_unit * (1 - (line.discount or 0.0) / 100.0)
+                if line.company_id.tax_calculation_rounding_method == 'round_globally':
+                    tax = line.tax_id.with_context(round=False)
+                else:
+                    tax = line.tax_id
+                taxes = tax.compute_all(price, line.order_id.currency_id, line.product_uom_qty,
+                    product=line.product_id, partner=line.order_id.partner_id)
+                amount_tax += (taxes['total_included'] - taxes['total_excluded'])
+                amount_untaxed += taxes['total_excluded']
+
             order.update({
                 'amount_untaxed': order.pricelist_id.currency_id.round(amount_untaxed),
                 'amount_tax': order.pricelist_id.currency_id.round(amount_tax),
```

For a patch without field changes but beware the performances impact on large SO

**Comment by pedrobaeza** [comment]
Thank you very much for the alternative patch, Martin. Indeed, that's the original reason for avoiding that solution, as there are already other performance killers in large orders, and I don't want to add other one, but let's see what people says. That fields are very rare and underused, so the impact is minimal.

**Comment by hbrunn** [comment]
we need to do the same thing as upstream does, so changing field types here is not an option if it's not changed in upstream too. Can we change the patch such that the speed penalty only happens with `round_globally` enabled?

**Comment by pedrobaeza** [comment]
Yeah, of course it can be only on that case. Doing that then.

**Comment by pedrobaeza** [comment]
I have changed the compute method now. There's also a possible drawback, that is potential extensions that changes the total computation now have to rewrite 2 compute methods (the line and the total one). I keep both commits for you to compare the possible solutions.

**Comment by StefanRijnhart** [comment]
2nd solution looks good to me! :+1:

**Comment by carlosdauden** [comment]
https://github.com/odoo/odoo/commit/291a94192c77e75e1f338a92ccc71898d7484433

**Comment by pedrobaeza** [comment]
This branch now has conflicts

**Pull request closed without merging**
