### PR TITLE
Fix analytic view duplication

### PR DESCRIPTION
**Pull request by ccomb**
backport of odoo/odoo#6368

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
A question of best practices here: should you not check if someone already passed certain values for these keys in the call to copy_data() so that you don't overwrite them? As in https://github.com/odoo/odoo/blob/8.0/addons/project/project.py#L700

**Comment by ccomb** [comment]
@StefanRijnhart you're right, I've replaced with setdefault, which won't overwrite.

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
