### PR TITLE
[9.0][FIX] mail: Avoid merging thread guess methods

### PR DESCRIPTION
**Pull request by yajo**
Before this patch, thread guessing method number 2 was polluting method number 5.

You can see that method number 2 was setting the `thread_id` variable in a place where it still didn't know if it was going to be used: https://github.com/OCA/OCB/blob/f63efa19843cd95b29e8cec82cf93a2d126d278a/addons/mail/models/mail_thread.py#L1013

You can also see that, in case number 2 didn't pass, method 5 also used that `thread_id` variable for its own purposes: https://github.com/OCA/OCB/blob/f63efa19843cd95b29e8cec82cf93a2d126d278a/addons/mail/models/mail_thread.py#L1093

In practice, this means that, if these conditions happen:

1. You configure `crm.lead` as a fallback model for your incoming mail server.
2. You send a message to Mr. Demo from a Sales Order with ID 100.
3. You delete the thread (delete the SO 100).
4. Mr. Demo responds via email.
5. A `crm.lead` with ID 100 exists.

Then, Mr. Demo's response would be processed as a response to `crm.lead` 100, instead of creating a new `crm.lead`.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
What a mangling in variable names! I suppose this has been fixed in higher version in core, isn't it?

**Comment by pedrobaeza** [comment]
@chienandalu can you please review?

**Comment by yajo** [comment]
> I suppose this has been fixed in higher version in core, isn't it?

Yes, simply the 6.1 backwards compatibility was dropped in v10. However I suspect the bug may exist in OCB 8 still.

**Comment by pedrobaeza** [comment]
OK, 8.0 is out of our support cycle, so anyone with this problem can propose the patch.

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Pull request merged**
