### PR TITLE
[FIX] account.voucher settings dates regardless of user timezone

### PR DESCRIPTION
**Pull request by veloutin**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you propose the same upstream?

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Yes, please reference your upstream PR here.

**Comment by veloutin** [comment]
@pedrobaeza, @StefanRijnhart : I have cherry-picked this change into a bigger PR: 
Upstream: https://github.com/odoo/odoo/pull/6586
OCB: https://github.com/OCA/OCB/pull/199

**Pull request closed without merging**
