### PR TITLE
[REF] Add a hook for import fake fields

### PR DESCRIPTION
**Pull request by sylvainc**
A trivial hook needed for inheritance.

Best regards.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
With this, you are going to create code that only runs on OCB. It's a hard way, specially for the migration to future versions.

I'm not sure if this is convenient. Let's see what others think.

**Comment by chafique-delli** [comment]
I think that there is not a major change so that this PR is refused on the branch Odoo. 
Best regards.

**Comment by gdgellatly** [comment]
Hi

I'm not sure about Pedro's concerns but from a technical standpoint i think
this patch can be improved.

Having a non pure function which does some of the task of setting fields
while leaving the rest in the existing function limits its usefulness,
mostly to that one function. In any case it is so simple to make this pure
we should.

Rather than add_fake_fields I would prefer to see a function called
get_export_fields that takes self as an argument and returns the fields
dict removing the responsibility entirely from extract.

But at the very least instead of passing a dict, changing it in place, then
reassigning it would be better served with an update call.

**Comment by pedrobaeza** [comment]
@gdgellatly, it's just that if you overwrite _add_fake_fields_ (or _get_export_fields_) method in your module, this will only works on OCB, not on Odoo standard.

**Comment by gdgellatly** [comment]
Of course, you make perfect sense and indeed this probably shouldn't land
here, I've already got problems with OCB for adding arguments to existing
functions meaning I have to maintain 2 module versions so should have
realised .

**Comment by sylvainc** [comment]
Hello @pedrobaeza , @gdgellatly 

Thank for your answers.

This hook has been accepted upstream
https://github.com/odoo/odoo/commit/fa18530210fc1763ce7d20768cde1e640c5882b0

Best regards.

**Comment by pedrobaeza** [comment]
Very good news!

**Pull request closed without merging**
