### PR TITLE
web : Allow database selection when list_db = False

### PR DESCRIPTION
**Pull request by clb-openfire**
Fix bug reported since v7 : https://bugs.launchpad.net/openerp-web/+bug/1268510

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
I'm afraid I don't understand. With your patch, I do get the database text field, which seems like an improvement. But switching databases then still seems impossible. As you write in your original bug report: "Once a database name is entered, the field disappears, and won't appear unless you clean your browser's cache". That seems to be still the case with this patch.

**Comment by clb-openfire** [comment]
Once you select a database, the login page is read from it (view stored in database from web/views/webclient_templates.xml)
Thus, you need to update web module in the selected database after applying this patch.

**Comment by StefanRijnhart** [comment]
My bad! And I see your change fixes this now.

A large part of the change is a reindentation because of the new condition. I see that template conditions are not always followed by extra indentation elsewhere in this file. The change would be simpler without this reindentation, and it may spare us from solving a conflict if you undid it. Would that be acceptable to you?

**Comment by clb-openfire** [comment]
No problem, it's done.

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Comment by pedrobaeza** [comment]
Is this intended for v9 or for v8?

**Comment by clb-openfire** [comment]
This patch is for v9. A patch for v7 is given in the above link to launchpad.
I've never tried on v8, I don't know if any of these two work on it.

**Comment by pedrobaeza** [comment]
Thanks for the clarification. Can you please check Runbot and Travis status to see the problem?

**Comment by StefanRijnhart** [comment]
CI problems are unrelated. OCB 9.0 does not have a travis.yml yet, and Runbot should blacklist alternative theme modules.

**Comment by pedrobaeza** [comment]
Ah, OK, then :+1:

**Pull request merged**
