### PR TITLE
migrate marketing and project_timesheet code from 7.0 to 9.0

### PR DESCRIPTION
**Pull request by mFlayyan**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Sorry, but OCB is not intended for that: it's only for bug fixing backports, but the stability policy is similar to Odoo (no DB changes). Your title is also incorrect. You are applying against 9.0, not 10.0.

**Comment by mFlayyan** [comment]
but nothing in the db has changed ! it is just migrating model code from 7.0 to 9.0

**Comment by pedrobaeza** [comment]
Yeah, but it's a large change that will provoke conflicts for sure every night when we merge changes from upstream. If you want new API, go to v10.

**Comment by mFlayyan** [comment]
I am not sure if I can agree with you or not, since by this way the OCB models can not be migrated forever !

**Comment by pedrobaeza** [comment]
I don't get your point, but you have OpenUgprade for migrating.

**Comment by gdgellatly** [comment]
@mFlayyan OCB is a bugfix branch for backporting changes that the community feels is necessary in older versions that Odoo does not want to or cannot backport for some reason.  So yes you are correct, the v9 branch will never be migrated to new api if it isn't done so upstream.  However, v10 starts afresh from upstream Odoo and there is a merge process that happens.

**Pull request closed without merging**
