### PR TITLE
[8.0] Tax calculate precision fix

### PR DESCRIPTION
**Pull request by levkar**
Description of the issue/feature this PR addresses:

When round globally is selected, this method still rounds it to account precision (instead of +5). This causes product cost and account move entries to be wrong since it is being calculated from output of this method.

Current behavior before PR:

    Set Price Precision to 5 digits, Account Precision to 2 digits, currency rounding to round globally.
    Create a product with real time valuation and set input, output and valuation account on its product category.
    Create a purchase with a product with amount 100 and unit price 1.12345
    Confirm order, make the transfer, confirm invoice.
    Amount is calculated as 112.35 in invoice accounting move.
    Amount is calculated as 112.00 in inventory valuation accounting move.

Desired behavior after PR is merged:

    Set Price Precision to 5 digits, Account Precision to 2 digits, currency rounding to round globally.
    Create a product with real time valuation and set input, output and valuation account on its product category.
    Create a purchase with a product with amount 100 and unit price 1.12345
    Confirm order, make the transfer, confirm invoice.
    Amount is calculated as 112.35 in invoice accounting move.
    Amount is calculated as 112.35 in inventory valuation accounting move.

### CODE REVIEW

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Looks like a good fix, but it changes a method signature so we can't takeit. It needs to be merged in upstream Odoo. Please propose there.

**Comment by levkar** [comment]
Thanks for the review. I couldn't find a way to send this since there is no context in this function.

We spend serious amount of time to recover the hazard caused by this problem. Once the cost is wrong on the quant, then everything goes wrong afterwards. It wasn't even possible to correct records in complex customers (e.g. using landed costs).  Considering its importance we applied this commit on our production branch.

I am closing it here. Thanks again.

**Comment by StefanRijnhart** [comment]
@levkar So, did you create a PR against Odoo? They'd be happy to take it.

**Comment by levkar** [comment]
Yes I did.

https://github.com/odoo/odoo/pull/15680

They fixed this in v9 and v10 but they don't seem to be interested to get it fixed it in v8.

Here's their fix:

https://github.com/odoo/odoo/commit/2e4777bb3288b8c56b2e747d07c0c2d049fa007e

For those who use product price with more than 2 digits, this fix is very important.

**Pull request closed without merging**
