### PR TITLE
[7.0] use the pypi version of PyChart

### PR DESCRIPTION
**Pull request by gurneyalex**
this will save pain when download.gna.org is down
https://pypi.python.org/pypi/Python-Chart/1.39

Backport of #250 to 7.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Also :+1:

**Comment by lmignon** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
In the 8.0 version we also replaced the occurrence of pychart in the py2exe part. You could do that here as well: https://github.com/gurneyalex/odoo/blob/7.0-pychart-in-pypi/setup.py#L80

**Comment by gurneyalex** [comment]
@StefanRijnhart done

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Pull request merged**
