### PR TITLE
Procurement schedulers now catch all exceptions and log them

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to improve the procurement schedulers: instead of just catching the SQL Operational Errors (and retrying them later in one case), they catch all exceptions (so that the scheduled task is not stopped), log them as warnings, and still retrying the one case for OperationalError.

It was also done for upstream in https://github.com/odoo/odoo/pull/3841 .

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Seems OK, but just for curiosity, what other exceptions have you found here?

:+1:

**Comment by mdietrichc2c** [comment]
@pedrobaeza I did have an osv.except_osv exception, from the _check_supplier_info() method in addons/purchase/purchase.py (line 1200), since a product was wrongly set. I'm actually not sure if logging and continuing is the best case here; on one hand, the scheduler should continue to process other procurements, on the other, the error should be visible.
Maybe a "procurement report" like in V5/6 would be better to spot non-concurrency errors.

**Comment by pedrobaeza** [comment]
I agree with you that the error output of procurements is not good, but OCB policy doesn't allow us to add fields except very counted exceptions. Maybe we can propose a change to have attached this type of comments, because is justified enough.

**Comment by clonedagain** [comment]
You could write a procurement report to the admin's chatter instead of adding a new field.
:+1:  for the current PR.

**Comment by gurneyalex** [comment]
I'd rather not have a WARN in the log for all OperationalError occuring during a scheduler run. Could we limit this to only the other unexpected errors?

Also it would be nice to have also the procurement name in the log, not only the id (easier to look for them in the web interface)

**Comment by mdietrichc2c** [comment]
@gurneyalex thanks for the comment, it's fixed now.

**Comment by vrenaville** [comment]
:+1:  thanks for the fix

**Pull request merged**
