### PR TITLE
[11.0][UPD] l10n_es: multiple backports

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**
Description of the issue/feature this PR addresses:
Backports from 14.0 and 16.0

* pending commit https://github.com/OCA/OCB/commit/ef8c7e2b693584f5bba7c1d3b6418bef8e6a256f

Current behavior before PR:
Update branch 11.0

Desired behavior after PR is merged:
Update spanish localization with newest developments

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This must done in l10n_es_extra_data, not here.

**Comment by ljsalvatierra-factorlibre** [comment]
> This must done in l10n_es_extra_data, not here.

Ok, is there something (of all the changes inside the 20 commits) that should be done here?

**Comment by pedrobaeza** [comment]
I don't think so.

**Comment by ljsalvatierra-factorlibre** [comment]
> I don't think so.

Ok, thank you and sorry for the trouble.

**Comment by pedrobaeza** [comment]
No problem. Remember also that `[UPD]` is not a valid tag.

**Pull request closed without merging**
