### PR TITLE
[FIX] Resolve default_composition_mode key missing

### PR DESCRIPTION
**Pull request by JaHicks**
Email previews were being prevented when default_composition_mode key was not available in context.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, @JaHicks, have you made the same PR in official odoo branch (for 8.0)?

BTW, :+1:

**Comment by JaHicks** [comment]
Hi @pedrobaeza, thanks for the response.
The same issue does not exist in 8.0 because the "result = base64.b64encode(result)" is not inside an "if" block.  This possibly suggests that another fix has been included in 7.0, but not 8.0.

**Comment by pedrobaeza** [comment]
OK, I remember. In fact, I was the one that makes that patch on OCB, and try to get it to core, but with no success for the momment. I made it without get because in all tests, I always get a value, but it's safer this way.

Do you want to try again the whole patch as an Odoo PR? I tried it on Launchpad, and maybe it got lost.

Thanks again.

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
