### PR TITLE
[8.0][BACKPORT][FIX] mail: log correct user deleting the record

### PR DESCRIPTION
**Pull request by yajo**
Backport of https://github.com/odoo/odoo/commit/91486656ab584cbb7a1f48543ccfe37fb386d850 for security.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by nilshamerlinck** [comment]
It's either this PR or https://github.com/OCA/OCB/pull/776 but can't be both ;-)

**Comment by pedrobaeza** [comment]
Why GitHub has let me merged both? I would swear I had a déjà vu seeing this PR but I didn't associated to a duplicated PR.

**Comment by yajo** [comment]
Yikes, I didn't see that one!

**Comment by pedrobaeza** [comment]
Only one commit has arrived to branch, so everything OK.

**Pull request merged**
