### PR TITLE
Re-add revision 9296 from lp:ocb-addons/7.0

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This bug was fixed by http://bazaar.launchpad.net/~ocb/ocb-addons/7.0/revision/9296 , but it disappeared from OCB during the Github move.

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
Also done upstream in https://github.com/odoo/odoo/pull/3930

**Comment by pedrobaeza** [comment]
Thanks for resubmitting. If you look for that revision here: https://github.com/OCA/OCB/wiki/lp2git-replay, you will find:

```
Committing http://bazaar.launchpad.net/~ocb/ocb-addons/7.0/revision/9296
fixes https://launchpad.net/bugs/1188593
Patch failed, reverting
--> Patch not replayed. PR pending.
```

So it is clearly said that the patch was not merged. But I checked for all these errors to remake PRs, so I don't how can I missed that one. Maybe we should check again the list for any other one...

:+1:

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
