### PR TITLE
[FIX] use matching operator to get patner from email in mail_thread.

### PR DESCRIPTION
**Pull request by nbessi**
Fix issue #856.

The current operator to match email and partner is ilike but it add wildcards around right criteria so we can have false positive.

eg I'v got an email in my customer base like a_mail@provider.com

If I recive a mail from mail@provider.com as ilike operator uses wildcards a_mail@provider.com can potentially be matched.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Nicolas, have you made the same PR against odoo master and odoo 7.0?

Regards.

**Comment by nbessi** [comment]
@pedrobaeza yes:
https://github.com/odoo/odoo/pull/856
https://github.com/odoo/odoo/pull/857

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: (code review)

Thanks

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
