### PR TITLE
[FIX] don't mess with the dataset's ids

### PR DESCRIPTION
**Pull request by hbrunn**
https://code.launchpad.net/~therp-nl/ocb-web/lp1303829/+merge/214542

### CODE REVIEW

**Comment by guewen** [comment]
Do you know why this dance with the ids was there?

**Comment by hbrunn** [comment]
Not the faintest idea I must admit. bzr blame back then didn't give any hints unfortunately.

It was introduced here:

```
$bzr log -r 3518
------------------------------------------------------------
revno: 3518 [merge]
committer: Fabien Meghazi <fme@openerp.com>
branch nick: trunk
timestamp: Wed 2012-11-28 18:13:25 +0100
message:
  [MERGE] Fix kanban dataset.ids missing when using 'Show more' button
------------------------------------------------------------
Use --include-merged or -n0 to see merged revisions.
$ bzr diff -r 3517..3518
=== modified file 'addons/web_kanban/static/src/css/kanban.css'
--- addons/web_kanban/static/src/css/kanban.css 2012-11-15 14:30:59 +0000
+++ addons/web_kanban/static/src/css/kanban.css 2012-11-27 08:49:17 +0000
@@ -279,6 +279,7 @@
 .openerp .oe_kanban_view.oe_kanban_ungrouped .oe_kanban_column .oe_kanban_record {
   display: inline-block;
   padding: 2px;
+  vertical-align: top;
   box-sizing: border-box;
   -moz-box-sizing: border-box;
   -webkit-box-sizing: border-box;

=== modified file 'addons/web_kanban/static/src/css/kanban.sass'
--- addons/web_kanban/static/src/css/kanban.sass    2012-11-15 14:30:59 +0000
+++ addons/web_kanban/static/src/css/kanban.sass    2012-11-27 08:49:17 +0000
@@ -266,6 +266,7 @@
         .oe_kanban_record
             display: inline-block
             padding: 2px
+            vertical-align: top
             box-sizing: border-box
             -moz-box-sizing: border-box
             -webkit-box-sizing: border-box

=== modified file 'addons/web_kanban/static/src/js/kanban.js'
--- addons/web_kanban/static/src/js/kanban.js   2012-11-28 14:59:41 +0000
+++ addons/web_kanban/static/src/js/kanban.js   2012-11-28 17:13:25 +0000
@@ -642,14 +642,14 @@
     },
     do_show_more: function(evt) {
         var self = this;
+        var ids = self.view.dataset.ids.splice(0);
         return this.dataset.read_slice(this.view.fields_keys.concat(['__last_update']), {
             'limit': self.view.limit,
             'offset': self.dataset_offset += self.view.limit
         }).then(function(records) {
-            records.forEach(function(r) {
-                self.view.dataset.ids.push(r.id);
-            });
+            self.view.dataset.ids = ids.concat(self.view.dataset.ids);
             self.do_add_records(records);
+            self.compute_cards_auto_height();
             return records;
         });
     },
```

To me that looks a lot like working around a problem in read_slice that was fixed afterwards

**Comment by gurneyalex** [comment]
:+1:!

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
Already merged, still, thanks for the explanation @hbrunn :+1:

**Pull request merged**
