### PR TITLE
Fix move operation link creation

### PR DESCRIPTION
**Pull request by florian-dacosta**
Here is the Odoo PR with description : https://github.com/odoo/odoo/pull/14016
Here is a test to easily reproduce the bug from a community module : https://github.com/OCA/sale-workflow/pull/351
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Thanks, but can you adopt the changes on the upstream PR?

**Comment by florian-dacosta** [comment]
@StefanRijnhart 
On the upstream PR, changes are done already, should I make it here too or close the PR?
Since I think it won't be merged here if it is not upstream?

**Comment by StefanRijnhart** [comment]
I think the response on the upstream PR was positive, so all the more reason to merge into OCB. Please update this PR if you can find the time.

**Comment by pedrobaeza** [comment]
Is this also happening in v8?

**Comment by florian-dacosta** [comment]
Of course, I applied the same changes than the PR upstream.

I am not sure about the v8, as I did not test, but my guess would be that the problem is also happening in v8.
And probably also in v10, I am not sure either...
But from what I see, it still modify a list which is beeing looped, it can't be good!

The best would be if PR is merged upstream, so Odoo would port the fix to v10 and master at least.

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
