### PR TITLE
[FIX] #3670 Don't override previous value if no journal is found

### PR DESCRIPTION
**Pull request by ccomb**
backport PR #3671 for issue #3670

### CODE REVIEW

**Comment by pedrobaeza** [comment]
See my comment https://github.com/odoo/odoo/issues/3670#issuecomment-91308238

**Comment by gurneyalex** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by yvaucher** [comment]
@pedrobaeza comment was replied here https://github.com/odoo/odoo/issues/3670#issuecomment-91317518

**Pull request merged**
