### PR TITLE
[10.0] Add .travis.yml

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Uhm, almost... It seems JS tours are not correctly executed. Maybe you need something extra on Travis file catched from the one in website repo: https://github.com/OCA/website/blob/9.0/.travis.yml#L30

**Comment by guewen** [comment]
The version of phantomjs installed on Travis does not support the MutationObserver API which is required for Odoo. I updated to phantomjs 2.1.1 that support it and the js tour tests pass. But the tests of `stock_landed_costs` don't, which is weird...

**Comment by pedrobaeza** [comment]
This is the list of non-installed modules on Odoo's runbot. We should mimic it:

* auth_ldap
* base_gengo
* hw_blackbox_be
* hw_escpos
* hw_posbox_homepage
* hw_posbox_upgrade
* hw_proxy
* hw_scale
* hw_scanner
* l10n_ae
* l10n_ar
* l10n_at
* l10n_au
* l10n_be
* l10n_be_hr_payroll
* l10n_be_hr_payroll_account
* l10n_be_intrastat
* l10n_be_invoice_bba
* l10n_bo
* l10n_br
* l10n_ca
* l10n_ch
* l10n_cl
* l10n_cn
* l10n_cn_small_business
* l10n_cn_standard
* l10n_co
* l10n_cr
* l10n_de
* l10n_de_skr03
* l10n_de_skr04
* l10n_do
* l10n_ec
* l10n_es
* l10n_et
* l10n_eu_service
* l10n_fr
* l10n_fr_fec
* l10n_fr_hr_payroll
* l10n_gr
* l10n_gt
* l10n_hn
* l10n_hr
* l10n_hu
* l10n_in
* l10n_in_hr_payroll
* l10n_it
* l10n_jp
* l10n_lu
* l10n_ma
* l10n_multilang
* l10n_mx
* l10n_nl
* l10n_no
* l10n_nz
* l10n_pa
* l10n_pe
* l10n_pl
* l10n_pt
* l10n_ro
* l10n_sa
* l10n_sg
* l10n_si
* l10n_syscohada
* l10n_th
* l10n_tr
* l10n_uk
* l10n_uy
* l10n_ve
* l10n_vn
* pos_cache
* theme_bootswatch
* theme_default
* website_gengo

**Comment by guewen** [comment]
Thanks, sure, I'll update the config.

**Comment by guewen** [comment]
Better!

Remaining:

```
2016-12-22 10:10:38,713 23465 INFO openerp_test odoo.addons.test_pylint.tests.test_pylint: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2016-12-22 10:10:39,073 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: FAIL
2016-12-22 10:10:39,075 23465 INFO openerp_test odoo.addons.test_pylint.tests.test_pylint: ======================================================================
2016-12-22 10:10:39,075 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: FAIL: test_pylint (odoo.addons.test_pylint.tests.test_pylint.TestPyLint)
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: Traceback (most recent call last):
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: `   File "/home/travis/OCB-10.0/odoo/addons/test_pylint/tests/test_pylint.py", line 61, in test_pylint
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: `     self.fail(msg="\n" + out)
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: ` AssertionError:
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: `
2016-12-22 10:10:39,076 23465 INFO openerp_test odoo.addons.test_pylint.tests.test_pylint: Ran 1 test in 0.363s
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.addons.test_pylint.tests.test_pylint: FAILED
2016-12-22 10:10:39,076 23465 INFO openerp_test odoo.addons.test_pylint.tests.test_pylint:  (failures=1)
2016-12-22 10:10:39,076 23465 ERROR openerp_test odoo.modules.module: Module test_pylint: 1 failures, 0 errors
```

```
2016-12-22 10:21:07,513 23465 INFO openerp_test odoo.modules.module: odoo.addons.website_project.tests.test_access_rights running tests.
2016-12-22 10:21:30,899 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: ERROR
2016-12-22 10:21:30,900 23465 INFO openerp_test odoo.addons.website_project.tests.test_access_rights: ======================================================================
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: ERROR: setUpClass (odoo.addons.website_project.tests.test_access_rights.TestPortalProject)
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: Traceback (most recent call last):
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/project/tests/test_project_base.py", line 40, in setUpClass
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     'project_id': cls.project_pigs.id})
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/project/models/project.py", line 510, in create
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     task = super(Task, self.with_context(context)).create(vals)
2016-12-22 10:21:30,900 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/mail/models/mail_thread.py", line 228, in create
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     thread = super(MailThread, self).create(values)
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/pad/models/pad.py", line 112, in create
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     pad_info = self.with_context(**ctx).pad_generate_url()
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/pad/models/pad.py", line 55, in pad_generate_url
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     myPad.createPad(path)
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/pad/py_etherpad/__init__.py", line 208, in createPad
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     return self.call("createPad", params)
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/home/travis/OCB-10.0/addons/pad/py_etherpad/__init__.py", line 40, in call
2016-12-22 10:21:30,901 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     response = opener.open(request, timeout=self.TIMEOUT)
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/urllib2.py", line 400, in open
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     response = self._open(req, data)
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/urllib2.py", line 418, in _open
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     '_open', req)
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     result = func(*args)
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/urllib2.py", line 1215, in https_open
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     return self.do_open(httplib.HTTPSConnection, req)
2016-12-22 10:21:30,902 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     r = h.getresponse(buffering=True)
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     response.begin()
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/httplib.py", line 407, in begin
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     version, status, reason = self._read_status()
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     line = self.fp.readline()
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/socket.py", line 447, in readline
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     data = self._sock.recv(self._rbufsize)
2016-12-22 10:21:30,903 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/ssl.py", line 241, in recv
2016-12-22 10:21:30,904 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     return self.read(buflen)
2016-12-22 10:21:30,904 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `   File "/usr/lib/python2.7/ssl.py", line 160, in read
2016-12-22 10:21:30,904 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: `     return self._sslobj.read(len)
2016-12-22 10:21:30,904 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: ` SSLError: The read operation timed out
2016-12-22 10:21:30,904 23465 INFO openerp_test odoo.addons.website_project.tests.test_access_rights: Ran 0 tests in 23.387s
2016-12-22 10:21:30,904 23465 ERROR openerp_test odoo.addons.website_project.tests.test_access_rights: FAILED
2016-12-22 10:21:30,904 23465 INFO openerp_test odoo.addons.website_project.tests.test_access_rights:  (errors=1)
2016-12-22 10:21:30,904 23465 INFO openerp_test odoo.modules.module: odoo.addons.website_project.tests.test_access_rights tested in 23.39s, 0 queries
```

**Comment by pedrobaeza** [comment]
I have run again the test and only test_pylint is failing, and this one comes from MQT. I have blacklisted it to see.

**Comment by pedrobaeza** [comment]
No luck, there's still the PhantomJS error.

**Comment by pedrobaeza** [comment]
@hbrunn, maybe you can help here

**Comment by pedrobaeza** [comment]
This one can be closed as there's now a Travis working file.

**Pull request closed without merging**
