### PR TITLE
8.0 pos child taxes fva

### PR DESCRIPTION
**Pull request by jnbrunet**
This is based on the [8.0 pos child taxes fva pull request](https://github.com/odoo/odoo/pull/1835) from the odoo-dev repository. Unfortunately, the change was creating a bug when the POS was creating an invoice of an order containing child taxes. Since the 1835 pull request is almost 8 month old, I'm creating this one that should work correctly.

This pull request contains the odoo-dev commit and a fix for the invoice bug. Normally, you could checkout the odoo.git 8.0 branch and cherry-pick the last two commit of my branch if you want the child taxes to work in the point of sale module.

### CODE REVIEW

**Comment by mcassuto** [comment]
@jnbrunet even manually, unable to apply this patch as per today against OCA/OCB.

Could you kindly help on this ?

**Comment by jnbrunet** [comment]
@mcassuto You should probably look at the changes made in [58a48](https://github.com/odoo/odoo/commit/58a481329eb1ec4074a08e12b89fdbd2aaa35343) by @mart-e as I believe it is the clean way to fix the bug.

**Comment by mcassuto** [comment]
Hi @jnbrunet ,

yes the patch is here, merged into OCA/OCB, branch 8.0,
but still does not work:
- nor on the POS interface
- nor on the POS receipt

However the tax computation on the invoice generated from the invoice is correct.

Am I doing something wrong ?
I also checked my taxes setup : everything is working fine since it is working within the standard invoicing process.

**Comment by mart-e** [comment]
Indeed the commit 58a481329eb1ec4074a08e12b89fdbd2aaa35343 should fix the issue where child taxes are used. I haven't checked on the OCB branch but on odoo 8.0 you should not have this issue anymore.
Note that this was only responsible for the computation of the prices in the POS. Your report seems to be linked to the generated invoices so there may be a different bug (but we would need more details).

**Comment by mcassuto** [comment]
Hi mart-e,

As you can see on this screenshot, the issue is really about the the prices in the POS:


In fact, I am starting to wonder if it is not me doing something wrong: your patch is here,
but the whole behavior is exactly as the one we had on v7 : 100% tax, in the backend the order is not paid because the amounts do not match...

Could you quickly test the branch 8.0 on OCA/OCB ?

**Comment by mart-e** [comment]
Sorry, I have made a quick test on OCB 8.0 and it worked fine.
Parent Tax: Percentage 1.0, Tax on Children enabled
Child tax: Percentage 0.06

**Comment by mcassuto** [comment]
I agree : I restarted from scratch, rebuilding the all environment and I confirm it work on both repo OCA & odoo.
Sorry for that...

**Pull request closed without merging**
