### PR TITLE
Add menu action context while retrieving need action domain from model

### PR DESCRIPTION
**Pull request by codingforfun**
Add ability to provide context while getting need action count.

### CODE REVIEW

**Comment by gurneyalex** [comment]
@codingforfun thanks for the patch. Can you indicate the upstream PR on odoo/odoo?

**Comment by codingforfun** [comment]
I added upstream PR: https://github.com/odoo/odoo/pull/10092

**Comment by OSguard** [comment]
@gurneyalex can you change the label to "needs review"

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by OSguard** [comment]
:+1:

**Comment by OSguard** [comment]
@StefanRijnhart can now be merged?

**Comment by StefanRijnhart** [comment]
Sure!

**Pull request merged**
