### PR TITLE
Return model of created object in message_process()

### PR DESCRIPTION
**Pull request by codingforfun**
Overwrite 'message_route_process()' and 'message_process()' in mail.thread model to return the model name of the created object together with the returned id. 

This is a follow up to my previous PR which turned out to be not compatible with 8.0 API overrides. https://github.com/OCA/OCB/pull/346

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
What bug are you trying to fix exactly? If you want to retrieve the model for your own purposes, can't you push down a mutable object like a list or a dictionary down to the context and intercept the model at a second override and put it in the mutable?

**Comment by codingforfun** [comment]
@StefanRijnhart 

> What bug are you trying to fix exactly?

The returned ID is useless without a model. I need the model. 
In v7 the model was returned in the context but this has been changed in cbe2dbb. Now a copy of the context is used inside message_route_process() so the model is not accessible through the context any more. 

>  If you want to retrieve the model for your own purposes, can't you push down a mutable object like a list or a dictionary down to the context and intercept the model at a second override and put it in the mutable?

I don't fully understand your idea. 
Since the copy of the context is made in message_route_process() I can't see how it should be possible to get the model from this function without changing it at the core or overriding it by making an nearly exact copy of its code. I thought of adding another keyword argument, but I think this would brake other overrides of the function. Can you please explain your idea.

**Comment by StefanRijnhart** [comment]
I assume that you have an override on message_route_process(). Call this 

```
thread_models = []
self.with_context(thread_models=thread_models).message_route_process(...)
```

Then in an override of message_post(), you check if 'thread_model' and 'thread_models' are in the context and then you append the value of 'thread_model' to 'thread_models'. You should be able to find it back in your override of message_route_process() in the 'thread_models' list.

About your PR: changing the API like this in OCB is strongly discouraged because it introduces incompatibilities between OCB and Odoo.

**Comment by codingforfun** [comment]
The point here is, that the copy of the context is made at the beginning of the message_route_process(...) function. So your idea below don't work unless I also overwrite message_route_process(...) which isn't possible without making a complete copy of its body which would break all existing customizations to this function. 

```
thread_models = []
self.with_context(thread_models=thread_models).message_route_process(...)
```

**Comment by codingforfun** [comment]
The first line in the current version of message_route_process(...) is the problem.

``` python
context = dict(context or {})
```

**Comment by StefanRijnhart** [comment]
Your mutable variable should survive the copy, shouldn't it?

```
>>> context = {}
>>> thread_models = []
>>> context['thread_models'] = thread_models
>>> new_context = dict(context)
>>> new_context['thread_models'].append('res.partner')
>>> thread_models
['res.partner']
```

**Comment by codingforfun** [comment]
That's true, but that's not the point.
To use this mechanism I would have to make this change inside message_route_process(...). This isn't possible without making a nearly complete copy of its code. Since I don't get the value of thread_model out of this function with a simple override. 
Making it that way would break all possible customizations to this function made by other modules, wouldn't it?

**Comment by StefanRijnhart** [comment]
Well, my idea was to inject the model in the mutable context entry in an override of message_post, but this does not seem to work because message_post is called from the thread model instead of mail.thread itself. The thread model at that point has already inherited from mail.thread and any overrides on mail.thread::message_post are ignored. So you are right that there is no easy solution.

**Comment by codingforfun** [comment]
So what is your conclusion than? Is this an acceptable solution or is there a more elegant way of doing this? 
Another idea would be to port this stuff to 8.0 API. Then we could just return thread_id as a RecordSet which would include the model. This would solve the problem in the most Odooic way I think.

**Comment by StefanRijnhart** [comment]
Again, introducing a hook or functionality that does leads to incompatibility between Odoo and OCB is problematic. For your own use case, I would look into monkey patching the desired functionality into these methods or maintain an Odoo patch for your own personal use.

**Comment by codingforfun** [comment]
I close this because it seams this wont get merged and I found another workaround, however I think the basic issue still remains. This function is broken. Look e.g. at 

https://github.com/OCA/OCB/blob/8.0/addons/fetchmail/fetchmail.py#L252

This won't work.

**Pull request closed without merging**
