### PR TITLE
odoo-dev@6981960 into OCB

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to merge odoo-dev@6981960 into OCB, to resolve issue https://github.com/odoo/odoo/issues/3731

### CODE REVIEW

**Comment by pedrobaeza** [comment]
If this has been included in 7.0, it's a matter of hours that this will be included in next OCB synchronization. Is that the case?

**Comment by mdietrichc2c** [comment]
@pedrobaeza at the time, it was not yet planned for merge in odoo 7.0, which is why I made this PR on OCB; however, since then, @skh-odoo created a PR https://github.com/odoo/odoo/pull/4922 in order to merge it in odoo/7.0.

I'll put this PR on hold and push for the official one instead.

**Comment by yvaucher** [comment]
It seems we can proceed with this one. Still no move on officials.

:+1:

**Comment by pedrobaeza** [comment]
:+1: for me

**Pull request merged**
