### PR TITLE
[FIX] 'point_of_sale' add customer domain on  partner field of pos_order;

### PR DESCRIPTION
**Pull request by legalsylvain**
Add the same behaviour in pos_order form view as in sale_order form view; (domain of partner is restricted to customer = True);
_PR also available on odoo branch_ : https://github.com/odoo/odoo/pull/4770

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Do you need quotes around `True`?

**Comment by legalsylvain** [comment]
@pedrobaeza : thanks for your review. You're right, it works without quotes.

Regards.

**Comment by pedrobaeza** [comment]
:+1: 

Does this also applies to 8.0? If so, please make the corresponding issue and PRs to odoo and OCB.

**Comment by StefanRijnhart** [comment]
:+1:, thanks!

**Comment by hbrunn** [comment]
This is merged in upstream: https://github.com/odoo/odoo/commit/9769279e9605278281725ccc9fbbf321f5ba3524

**Pull request closed without merging**
