### PR TITLE
8.0 scheduler error handling

### PR DESCRIPTION
**Pull request by mistotebe**
This is another pull request that has sat with Odoo for a while here https://github.com/odoo/odoo/pull/7688.

Scheduler will fail the transaction in reordering rule processing and leak the cursor if there are any issues (configuration or otherwise). This can prevent the system from processing any further reordering rules at all while no issue is visible (all procurements that are created disappear with the transaction).

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Solved appropriately, thank you :+1:

**Comment by pedrobaeza** [comment]
:+1: for me also.

**Comment by mistotebe** [comment]
Just rebased onto latest OCB.

**Comment by Cedric-Pigeon** [comment]
:+1:  thanks

**Pull request merged**
