### PR TITLE
Call message_post for each record separately

### PR DESCRIPTION
**Pull request by igallart**
Fail message_post.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
I'm restarting travis tests as their failure seems unrelated.

**Comment by StefanRijnhart** [comment]
Tests are green after a restart. Have you got a link to the same PR to upstream Odoo please?

**Comment by igallart** [comment]
Who merged?

**Comment by StefanRijnhart** [comment]
@igallart Can you please add a link to your upstream PR on upstream Odoo as I asked you?

**Comment by igallart** [comment]
Close, it is resolved!

**Comment by StefanRijnhart** [comment]
Thanks for the follow up!

**Pull request closed without merging**
