### PR TITLE
[FIX][8.0] Schedule days backwards when days is negative number

### PR DESCRIPTION
**Pull request by antespi**
See https://github.com/odoo/odoo/pull/8208

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @max3903 @StefanRijnhart @jgrandguillaume @pedrobaeza @gurneyalex @dreispt  could any of you review with PR? This is a FIX proposed to Odoo,

We have added a new powerfull addon project_recalculated https://github.com/OCA/vertical-service/pull/90 but Travis CI build failed in OCA because that bug in Odoo https://github.com/odoo/odoo/pull/8208

Thanks

**Comment by pedrobaeza** [comment]
Please check upstream comments

**Comment by antespi** [comment]
Squash and rebase done, for fixing upstream comments.

**Comment by pedrobaeza** [comment]
Merged done on upstream, so I close

**Pull request closed without merging**
