### PR TITLE
[FIX] recompute old style stored related fields

### PR DESCRIPTION
**Pull request by hbrunn**
Upstream: https://github.com/odoo/odoo/pull/6774

This one is quite serious in my opinion, so please review soon

### CODE REVIEW

**Comment by ccomb** [comment]
I think this is also in v7, and v6
I guess the corresponding code in v7 is [here](https://github.com/OCA/OCB/blob/7.0/openerp/osv/orm.py#L1029)

**Comment by hbrunn** [comment]
@ccomb wow, I was not aware of this, thanks for pointing it out. Seems not to be as serious as I thought then if we could live with this for years, but still, fixing this seems a good idea to me...

**Comment by gurneyalex** [comment]
@hbrunn an automated test would be very welcome.

**Comment by hbrunn** [comment]
@gurneyalex added a test to `product`, as this is where I first ran into this problem, but I'm not entirely happy with having such a fundamental thing there. On the other hand, this doesn't seem to fit into any of the existing `test_*` modules and also doesn't really belong into `base` tests. But a new `test_oldstyle_fields` module seems a bit too much. Any thought about that? https://github.com/OCA/OCB/pull/214 could also be tested in such a module dedicated to oldstyle stuff, with the added benefit that we can simply throw that away when the old api gets deprecated.

**Comment by gurneyalex** [comment]
tested, works. 

:+1:

**Comment by hbrunn** [comment]
This was just rejected in upstream. I still propose to have it in OCB

**Comment by pedrobaeza** [comment]
Reading Odoo's explanations, it makes sense what they say, so maybe it's better to make these actions:
- Desestimate this PR
- Push to merge in Odoo's code comments with the same explanation of the PR.
- Push to documentation the same explanations.
- Add PRs in OCB/Odoo for affected old fields with this manual old store dictionary.

What do you think?

**Comment by pedrobaeza** [comment]
I close this according the comments on upstream and here, and yes, this has been finally not too much serious as there is not too much fields affected (even along OCA), as the trend has been to move to new API.

**Pull request closed without merging**
