### PR TITLE
Fix missing origin field in backorder pickings

### PR DESCRIPTION
**Pull request by alhashash**
This fixes a current ocb only bug that backorder picking does not copy `origin` field due to an incorrect fix of an old bug [lp:1098557](https://bugs.launchpad.net/openobject-addons/+bug/1098557) . A fix for the original bug has been just merged into 7.0 in commit  8af9fdfa0635f6a9f78320d59d5cfb7ff1b89df2.

This PR reverts and old commit and applies the new fix to prevent a conflict when merging the official 7.0 branch.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for doing the task.

:+1:

**Comment by clonedagain** [comment]
I agree on the principle, but would you please remove the 2nd commit? It's already upstream and you didn't retain the original author.

**Comment by alhashash** [comment]
@clonedagain The original author is correct (myself). I included it to prevent regression between merging this PR and merging from the upstream branch. It is a minor issue, so I'll remove it anyway.

**Comment by clonedagain** [comment]
@alhashash sorry for the confusion. :+1: for me

**Comment by yvaucher** [comment]
:+1: but needs rebase

**Comment by alhashash** [comment]
This is not longer required as the required change was properly done when 8af9fdfa0635f6a9f78320d59d5cfb7ff1b89df2 merged from upstream.

**Pull request closed without merging**
