### PR TITLE
[FIX] pos_restaurant: make config items inheritable 

### PR DESCRIPTION
**Pull request by primes2h**
Description of the issue/feature this PR addresses:

- point_of_sale config items have each an id attribute to be easily intercepted by other modules based on it. (eg. pos_restaurant)
- pos_restaurant extend point_of_sale config items without setting an id for new items added.
- So, for a new module depending upon pos_restaurant, it's not possible to intercept pos_restaurant config_items.

Current behavior before PR:

- pos_restaurant config items can't be intercepted to extend functionality.

Desired behavior after PR is merged:

- pos_restaurant config items are interceptable, so you can add features.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be proposed to odoo/odoo first.

**Comment by primes2h** [comment]
@pedrobaeza 

I did it 6 days ago.
https://github.com/odoo/odoo/pull/22720

**Comment by pedrobaeza** [comment]
Good to know then, because it's an OCB rule.

However, I'm not sure if we can accept this PR in OCB if Odoo doesn't accept it, as this will make that there will be modules only compatible with OCB, but not with Odoo, and that's another rule of this "bug-fixing derivative" (but not fork).

**Comment by primes2h** [comment]
You are right, I hope they'll take care of it soon.
This fix has a very good value and low risk impact.

**Comment by primes2h** [comment]
It has just been merged in Odoo. :-)

https://github.com/odoo/odoo/pull/22720

**Comment by pedrobaeza** [comment]
Great, closing.

**Pull request closed without merging**
