### PR TITLE
fix #3264 use parent_address

### PR DESCRIPTION
**Pull request by petrus-v**
This is a proposal to fix #3264 against v8.0 like PR #131 was for v7.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Also :+1:

**Comment by hbrunn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@StefanRijnhart, I have just seen now after merging that you have tagged it this as Upstream PR pending. Do you think this patch is going to change and it's better to revert this until the upstream is resolved?

**Comment by StefanRijnhart** [comment]
Ah, I commented about this on the 7.0 version indeed. Yes, we need to revert this as per OCB policy: upstream PR is required.

**Comment by petrus-v** [comment]
@StefanRijnhart,

Thanks for your reply, sorry about doing things silently, I'll be explicit next time.

New PR:
#152 => v8.0
#151 => v7.0

**Pull request merged**
