### PR TITLE
[IMP] mrp_repair: Added origin to the consumed product moves of the repair order

### PR DESCRIPTION
**Pull request by Daniel-CA**
Added origin to the consumed product moves of the repair order

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

Please reference/make the upstream PR to Odoo

**Comment by Daniel-CA** [comment]
Done in odoo#7808

**Comment by Daniel-CA** [comment]
Someone can check this?

**Comment by tafaRU** [comment]
:+1:

**Comment by eLBati** [comment]
LGTM :+1:

**Comment by Daniel-CA** [comment]
Thanks! :+1:

**Pull request merged**
