### PR TITLE
[7.0] Raise exception when ir_attachment creation fails

### PR DESCRIPTION
**Pull request by bwrsandman**
Odoo PR: https://github.com/odoo/odoo/pull/1514

> Currently, report creation failures are silent except for a message in the logs. We propose, with this pull request, to explicitely raise them to the user.

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
The problem is that for now, strings are not going to be translated due to the dependency to upstream translations.

**Comment by bwrsandman** [comment]
That's not really the point of this PR, this is more about seeing errors instead of hiding them.
As for:
-  `_('Error!')` That's already exported
- `_('Could not create saved report attachment')` You can insert an entry into `ir.translations` (not ideal, but it works)

**Comment by pedrobaeza** [comment]
Yeah, it's a possibility. I merge.

**Pull request merged**
