### PR TITLE
Sign odoo CLA

### PR DESCRIPTION
**Pull request by kutyel**
Description of the issue/feature this PR addresses:
Signed odoo CLA

Current behavior before PR:
Normal behavior

Desired behavior after PR is merged:
None
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This has to be done in odoo/odoo, not here. For OCA CLA, see https://odoo-community.org/page/cla

**Comment by kutyel** [comment]
@pedrobaeza I was trying to, but somehow forking the odoo/odoo repo sent me to my oca/ocb fork :confused:

**Comment by pedrobaeza** [comment]
Yes, because both are the same project. What you have to do is:
- Have 2 remotes: one for OCA/OCB and another for odoo/odoo.
- Have a master branch fetched from odoo/odoo.
- Make there the commit with your CLA.
- Push and make a PR against odoo/odoo.

Anyway, what you need know is the OCA CLA, not the Odoo CLA.

**Comment by kutyel** [comment]
Ok, perfect! Thanks, @pedrobaeza :+1:

**Pull request closed without merging**
