### PR TITLE
[fix] add travis.yml for v11 (closes #663)

### LINKED ISSUE #663: [11.0] build broken on travis
`Could not find .travis.yml, using standard configuration.`

Sounds like the same issue we had for #654.

Adding the same travis file w/ some update should fix it. See https://github.com/OCA/OCB/pull/654/commits/dd414476f62be3e85d0188c7b8276cb1162ebe81

### PR DESCRIPTION
**Pull request by simahawk**
@moylop260 ping

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think localization modules shouldn't be installed.

**Comment by simahawk** [comment]
@pedrobaeza I blacklisted all of them. Not sure if I did it properly (having l10n_* would be better) but let's see it gets green anyway.

**Comment by StefanRijnhart** [comment]
http woes in the tests. Are these reproducable locally?

**Comment by simahawk** [comment]
not tried yet. I'll try late today

**Comment by moylop260** [comment]
The LRU cache from odoo core is failing.
Maybe the issue is the current base source odoo/11.0
What about pull latest odoo/11.0?

**Review by moylop260 — APPROVED** [review]
This change is required to enable runbot instance available for oca/ocb#11.0
The error in the tests for OCB should be manage from https://github.com/OCA/OCB/issues/667

**Comment by pedrobaeza** [comment]
OK, merging then for having runbot.

**Pull request merged**
