### PR TITLE
[ADD] naively adding 8.0's .travis.yml to see what happens

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by hbrunn** [comment]
@rvalyi @pedrobaeza @dreispt here we go for https://github.com/OCA/OCB/issues/333#issuecomment-155822031

It's green now, but only because I exclude `website_sale_options` which seems to throw a legitimate error. Should we merge `travis.yml` as it is to have green PRs or with `website_sale_options` to increase the pain in order to get it fixed?

**Comment by dreispt** [comment]
I'm OK with that. :+1:

**Comment by pedrobaeza** [comment]
But this also happens with Odoo core?

**Comment by hbrunn** [comment]
No idea, I didn't test it with standard odoo. This commit looks promising: https://github.com/odoo/odoo/commit/5f30aaf9f442da6b3ce613be515ea776c50b5496, so after the next merge from upstream, things should be fine

**Comment by pedrobaeza** [comment]
OK, so I propose to re-add that module, wait for that commit to arrives to OCB, and then try again.

**Comment by hbrunn** [comment]
it's there, travis restarted

**Comment by pedrobaeza** [comment]
Cool, it's working! Runbot doesn't, but that's another history.

Merging

**Pull request merged**
