### PR TITLE
[FIX]-stock: Forecasted stock report is not multi-company compliant

### PR DESCRIPTION
**Pull request by hieulucky111**
Take into account multicompany in the report.stock.forecast.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jcdrubay** [comment]
Note: this is a backport from https://github.com/odoo/odoo/pull/20455/files which was merged only in master.

**Comment by jcdrubay** [comment]
@hieulucky111 thanks for your contribution.

Can you please:
 - Create a PR on odoo/odoo:11.0 and include the link of that you new in this PR?
 - Improve the description of your PR to match with the standard structure, see https://github.com/OCA/OCB/wiki/Contributing (Special Guidelines for OCB)

Thanks

**Comment by jcdrubay** [comment]
Travis failed with `The job exceeded the maximum time limit for jobs, and has been terminated.`

Hopefully this will be fixed with #734

**Comment by pedrobaeza** [comment]
If it was merged on master, I think this won't be merged on 11.0, so it's OK to only have it here in OCB.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
What you should make is to cherry-pick the commit instead of creating a new one.

**Review by gurneyalex — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
