### PR TITLE
[FIX] Allows to write log_access fields

### PR DESCRIPTION
**Pull request by antespi**
Adds a new method to BaseModel, called log_access_write, that allows to write log_access fields: `'create_uid', 'create_date', 'write_uid', 'write_date'`

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Antonio, as commented face to face, you should detect on regular write if one of the MAGIC_FIELDS is written, and then, don't overwrite it with empty value.

This should be also propose on Odoo upstream.

**Comment by antespi** [comment]
PR Odoo : https://github.com/odoo/odoo/pull/6387

**Comment by pedrobaeza** [comment]
In these lines:

https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L3859

You should check if the value already exists in the dictionary to avoid overwriting. This way, you avoid redifining the meaning of _log_access variable.

**Comment by antespi** [comment]
Is this error a problem of this PR code? or is a bug in travis configuration?
https://travis-ci.org/OCA/OCB/jobs/59228584

**Comment by gurneyalex** [comment]
the error was a problem on our runbot. I expect this to be solved.

**Comment by gurneyalex** [comment]
I'm not too fond of this. The audit columns are there for a reason, and if we allow anyone with write access to a record to change these values with a simple XMLRPC, then we are opening the doors to lots of possible abuse.

An admin level profile can update the columns using SQL, this is good enough for fixing mistakes. 

As is, I'm :-1: on this PR.

**Comment by StefanRijnhart** [comment]
:-1:, not a bug but a feature. Could be solved in a separate module.

**Comment by antespi** [comment]
@StefanRijnhart 
If I add this method in a model, using Odoo inheritance model, I'll have this feature available only for that model.
How do i implement this method to be available for all models at once?

@gurneyalex, As we can read in Odoo v8 ORM API doc: https://www.odoo.com/documentation/8.0/reference/orm.html#porting-from-the-old-api-to-the-new-api

> remove explicit definition of create_uid, create_date, write_uid and write_date fields: they are now created as regular "legitimate" fields, and can be read and written like any other field out-of-the-box

So, as I understand, Odoo is not considering this feature as a way for abusing. But I understand that regular web UI user should not change this values througth a view. XML-RPC is not user-friendly, is script-friendly.

BTW, i've just issued this to Odoo in https://github.com/odoo/odoo/issues/7005 in order to hear their opinion

**Comment by antespi** [comment]
Close because i'll try to implement via addon

**Pull request closed without merging**
