### PR TITLE
Check more thoroughly for active_id

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to avoid an issue, where the active_id currently in context when a delivery carrier is selected is not a sale order. In order to at least avoid issues with retrieving an empty browse, the active_id is verified as an existing sale.order.

Done for odoo/odoo in https://github.com/odoo/odoo/pull/5749

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why don't test active_model == 'sale.order'?

**Comment by mdietrichc2c** [comment]
@pedrobaeza I tried it, but AFAIK, the error I got depended on the URL still containing "active_id=<non-sale-order ID>. This meant that the active_model was sale.order, even if the ID wasn't.

I can still add the extra check, however.

**Comment by pedrobaeza** [comment]
You also don't need to make a search, but a browse, that returns also an empty recordset if id is not correct.

It's curious that active_model isn't correct... Maybe a bug?

**Comment by mdietrichc2c** [comment]
@pedrobaeza are you sure about the browse? I tested it, and it returned a browse_record, not a browse_null. That's why I went with the search().

As for active_model, maybe it took the one from the view, but the active_id was not updated? The customer that reported the issue told me it happens on creations (another user can access the sale order and set it, which is logical since the active_id is not defined).

**Comment by pedrobaeza** [comment]
You're right because I was talking on v8, where you can check if the record exists with `browse(order_id).exists()`. In v7 maybe there's no other mechanism.

Somebody knows?

**Comment by hbrunn** [comment]
no `exists()` in v7. When you browse a nonexisting id in v7, you'll always bet a browse_record and it will crash when you access a data property, so I think the `search()` approach is the right one.

But please investigate more into Pedro's `active_model` proposal, because that should be the right way to do it. If you get a non-matching `(active_model, active_id)` pair, that's a bug we have to fix.

**Comment by guewen** [comment]
And yet it exists in v7: https://github.com/odoo/odoo/blob/7.0/openerp/osv/orm.py#L5187-L5204

**Comment by mdietrichc2c** [comment]
Since the method exists, I replaced the check with it.
I also added the active_model check in the XML view; however, when I retried by adding "&active_id=" to the URL, the active_id was correctly using the check, and the ID was correct.

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1: 

Please fix you Odoo PR

**Pull request merged**
