### PR TITLE
[FIX] add context in bom_explode

### PR DESCRIPTION
**Pull request by bealdav**
add context in bom_explode in MRP module

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by clonedagain** [comment]
Is it proposed upstream yet?

**Comment by hbrunn** [comment]
it's in 8

**Comment by clonedagain** [comment]
Then looks :+1: to me, it shouldn't have bad effects.

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
