### PR TITLE
[FIX] don't mess up search's id order

### PR DESCRIPTION
**Pull request by hbrunn**
res_partner_category's name_search uses read, which is bad as it messes up the object's search order. This leads to weird (=the order the database returns) ordering as well in the Many2ManyTags widget's search pulldown as in tree views showing a list of categories.

This is a verbatim copy from the relevant section of https://github.com/odoo/odoo/commit/cbe2dbb672a6c55d86f2e515f9d1cdfee426ef80
(no cherrypick possible as this is a huge commit of evil), and as such, it also fixes display of multilevel categories, which doesn't seem bad to me either.

What's the policy here, there's no separate issue for this and it's already fixed in upstream - do we create another one on OCB or is this PR issue enough?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this can be enough, isn't it?

But about the patch itself, I think you can apply an order argument also to read method. In v8, browse method has been optimized, but not in v7. This specific model is not too troubled... What do you think?

**Comment by hbrunn** [comment]
could you point me to code for using order in read? I've never seen that. My initial own patch just did a
sorted(read([...]), key=lambda r: ids.index(r['id']))

I thought about if I should have problems with using browse here in v7, but agree with you, that should be harmless

**Comment by pedrobaeza** [comment]
You're right. Read doesn't include an order argument. We can accept this as is, and take care of other dangerous browse uses.

:+1:

**Comment by gurneyalex** [comment]
@hbrunn for the record, you really want to be careful with the idiom you mention: the complexity of this `sorted()` call is O(n²) because ids.index() is O(n).

**Comment by guewen** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
