### PR TITLE
cliking -> clicking

### PR DESCRIPTION
**Pull request by sammann-fnordkollektiv**
Corrected typo in message

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you make the correction on upstream odoo? Diverging this only here will make the translations useless.

**Comment by pedrobaeza** [comment]
Please group your four PRs in only one, because they are all related.

**Comment by bwrsandman** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Needs to be extended with the changes in #86, #87, #88. Therefore, setting to Needs fixing.

**Comment by clonedagain** [comment]
:-1: I'm pretty sure this will cause translation pain since all translations come from Launchpad using the upstream strings.
Please target upstream instead.

**Comment by pedrobaeza** [comment]
We can't use this as the translation source is from Odoo, so I close.

**Pull request closed without merging**
