### PR TITLE
[FIX] Fix incorrect merge 3e1d5be951fb8

### PR DESCRIPTION
**Pull request by alhashash**
Merge 3e1d5be951fb8 had a conflict that was incorrectly resolved. As a result, cannot validate invoices with 
tax line.

This PR correctly merges commit ab797f0cd8f76be2 to resolve the issue.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Agreed. After the conflict was resolved, this line was inconsistent with line 834 where the keys are checked. Removing the analytic argument restores the more recent change by @sbidoul.

Thanks! :+1:

**Comment by pedrobaeza** [comment]
For me also :+1:

**Comment by rvalyi** [comment]
:+1: agree

**Comment by hbrunn** [comment]
Thanks for picking that up! I wanted to keep changes from https://github.com/OCA/OCB/commit/fb7120d7b60aa04d5eb6580fb7dc769f8a46720c (btw: the rationale for conflict fixing is recorded here: https://github.com/OCA/OCB/wiki/Conflict-resolutions-OCB-synchronization) and didn't realize the commit removed the first occurrence of the analytic account id too - strangely enough without a conflict

**Comment by alhashash** [comment]
@hbrunn I think you are right. We should keep the analytic account in the key. Otherwise If two taxes share tax codes and account but have different analytic account, they will be grouped in one line with one analytic account. 

I made PR #83 to revert the original commit as the [target issue](https://bugs.launchpad.net/ocb-addons/+bug/1084822)  was already resolved in OCB.

**Pull request merged**
