### PR TITLE
[BCP][11.0] [IMP] base: restrict the authorized assets

### PR DESCRIPTION
**Pull request by florentx**
Backport https://github.com/odoo/odoo/commit/db47144f4e51442408596a48f275a0eb47ac5e13

### CODE REVIEW

**Comment by florentx** [comment]
Simpler alternative to PR #1086

**Review by yvaucher — APPROVED** [review]
Looks preferable to not change the signature of open_file.

LGTM

**Comment by florentx** [comment]
Actually, I've missed half of the patch when I refactored : `file_open` is indeed an additional layer of security, it verifies that the assets is in Odoo directories (addons or root path), else it raises a ValueError.

I've pushed the complement.

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
