### PR TITLE
[8.0][FIX] Do not listen when --no-xmlrpc is set

### PR DESCRIPTION
**Pull request by mistotebe**
This is a fix that we have been maintaining since 7.0 I believe and so far Odoo have not been able to get back to us and merge, so it seems unlikely to ever happen now.

Original text:
This is a fix for f04f409943b8bd8f4bd2653e368523d1cc0d8246, which only
prevented the workers from being spawned in Prefork mode, while the
socket was still being bound to - this is a problem when starting a
worker-only server as it cannot coexist with the XMLRPC server on the
same machine.

### CODE REVIEW

**Comment by dreispt** [comment]
Can you point at the upstream PR?

**Comment by mistotebe** [comment]
@dreispt: https://github.com/odoo/odoo/pull/1828

**Comment by dreispt** [comment]
The upstream PR advertises it was already fixed.

**Comment by mistotebe** [comment]
Nope, comment https://github.com/odoo/odoo/pull/1828#issuecomment-67789288 was about a different part of the system, the worker server is going through a different class and that's what this fixes.

**Comment by dreispt** [comment]
OK, and you now have an upstream "lgtm" from Anthony Lesuisse. Looks good.

**Comment by mistotebe** [comment]
Merged upstream

**Comment by dreispt** [comment]
Contratulations| :tada:

**Pull request closed without merging**
