### PR TITLE
Strip In-Reply-To header

### PR DESCRIPTION
**Pull request by jbq**
Header could be expressed like this:

In-Reply-To:
    <4ba8f246904b4fedb49fbab7945a7f82@AM3PR06MB433.eurprd06.prod.outl$$k.com>

The message lookup fails if header is not stripped

### CODE REVIEW

**Comment by yvaucher** [comment]
Is there any issue opened on https://github.com/odoo/odoo ?

**Comment by jbq** [comment]
See https://github.com/odoo/odoo/pull/1358

**Comment by yvaucher** [comment]
Please sync this patch with the one in odoo#1358

**Comment by jbq** [comment]
The two pull requests cannot be in sync because extra changes were made to OCA:7.0 in commit 0bee015 regarding the same bug

**Comment by yvaucher** [comment]
This commit has also landed on official odoo: https://github.com/odoo/odoo/commit/4bad513d29596abf2c614834a7592758186f0851

You will need to rebase your patch on odoo.

**Comment by jbq** [comment]
This has finally been merged upstream: https://github.com/odoo/odoo/pull/1358

**Comment by pedrobaeza** [comment]
We can close it then.

**Pull request closed without merging**
