### PR TITLE
[FIX] Removed check_super duplicate from res_users.py

### PR DESCRIPTION
**Pull request by PCatinean**

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

Can you do a backport to 7.0?

**Comment by guewen** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Please provide a link to the upstream PR

**Comment by PCatinean** [comment]
Upstream PR: https://github.com/odoo/odoo/pull/8403

**Comment by StefanRijnhart** [comment]
:+1: review and tested. Merging as per overwhelming support.

**Comment by gurneyalex** [comment]
merged upstream

**Pull request merged**
