### PR TITLE
website_portal : error on custom panel view

### PR DESCRIPTION
**Pull request by clb-openfire**
custom panel view on website user page is disabled by default, but when activated it showed an error

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks, looks good. Can you refer to the upstream PR onto Odoo 9.0 here? Create it if you haven't done so yet.

**Comment by clb-openfire** [comment]
Here is the link : https://github.com/odoo/odoo/pull/9432

**Comment by StefanRijnhart** [comment]
Thanks. Upstream CLA test breaks. Did you submit one?

**Comment by clb-openfire** [comment]
I did. It was integrated in odoo yesterday. Seems I still have to include it in the PR. I'll do it when I can free some time.

**Comment by StefanRijnhart** [comment]
Or just point to the revision that contains the CLA.

:+1: for this one then.

**Comment by clb-openfire** [comment]
I guess it is already the case, as it is a PR to odoo 9.0 in which cla is now merged (https://github.com/odoo/odoo/blob/9.0/doc/cla/corporate/openfire.md). Or I missed something.
Thanks for your review and your time.

**Comment by clb-openfire** [comment]
Fixed with https://github.com/odoo/odoo/commit/eb8c674d

**Comment by StefanRijnhart** [comment]
Thanks for the update!

**Pull request closed without merging**
