### PR TITLE
Backport client command discovery optimization

### PR DESCRIPTION
**Pull request by dreispt**
Using odoo commands currently imports every module sin the addons paths.
This is very slow and breaks if some error when imported (such as auth_ldap without LDAP libs installed on the system).

This is a backport of the solution already implemented on the master branch.
PR for 8.0: https://github.com/odoo/odoo/pull/6335
Fix on master: https://github.com/odoo/odoo/commit/4b387e73cb9cd051bd549e626b9255cf3bb5ea17

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Unfortunately, this does not fix the server loading all modules in the module path from openerp/http.py that have a static subdirectory. As such, your instance will still break on any module in one of the addons paths that contains a failing import, if they have this directory.

As an optimization when using Odoo commands :+1:

**Comment by dreispt** [comment]
I was not aware that the same issue occurred with web modules.
But yes, this fix is for the CLI commands use case.

**Comment by dreispt** [comment]
Hi! This is a direct backport of the code in master, from commit https://github.com/odoo/odoo/commit/4b387e73cb9cd051bd549e626b9255cf3bb5ea17
It improves drastically the speed to run the Odoo CLI commands.

**Comment by dreispt** [comment]
Merged upstream: https://github.com/odoo/odoo/commit/e20cf77ce0546ac37dbfabd8c71a0ab33cedc3d7

**Pull request closed without merging**
