### PR TITLE
9.0 fix res.config default get

### PR DESCRIPTION
**Pull request by gurneyalex**
upstream PR https://github.com/odoo/odoo/pull/10373

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
It seems there are some stray commits included.

**Comment by gurneyalex** [comment]
@StefanRijnhart fixed

**Comment by StefanRijnhart** [comment]
Clear analogy with https://github.com/odoo/odoo/pull/10373/files#diff-8afc2e490371312de7b57a87475fd72cL544 indeed. :+1:

**Comment by cyrilgdn** [comment]
:+1: I have the same issue with mrp.config.settings in my tests !

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
