### PR TITLE
[FIX] Removed check_super duplicate from res_users.py

### PR DESCRIPTION
**Pull request by PCatinean**

### CODE REVIEW

**Comment by PCatinean** [comment]
Backport of https://github.com/OCA/OCB/pull/322

**Comment by gurneyalex** [comment]
:+1:

**Comment by PCatinean** [comment]
Upstream PR: https://github.com/odoo/odoo/pull/8404

**Comment by StefanRijnhart** [comment]
Same as #322. Merging as per overwhelming support there.

**Comment by gurneyalex** [comment]
merged upstream

**Pull request merged**
