### PR TITLE
[FIX] honor required attribute on one2many fields

### PR DESCRIPTION
**Pull request by hbrunn**
upstream PR: https://github.com/odoo/odoo/pull/12248

@dreispt you might be interested in this one

### CODE REVIEW

**Comment by dreispt** [comment]
Nice!

**Comment by StefanRijnhart** [comment]
_cough_ https://bugs.launchpad.net/openerp-web/+bug/1013636

:+1:

**Comment by StefanRijnhart** [comment]
(this bug is a four year old toddler)

**Comment by PCatinean** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I made some questions on upstream that remains unanswered.

**Pull request merged**
