### PR TITLE
Fix/8.0/split up travis jobs

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Description of the issue/feature this PR addresses: #639

Additionally, fix website's test by adding the hidden dependency on portal, which is not auto-installed in OCB 8.0.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Ups, sorry, I deleted the branch without thinking that it will effect to the tests that are running 😥

**Comment by StefanRijnhart** [comment]
No problem! I had to restore the URL anyway.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I see overlapping in tests, as `INCLUDE=non_applications` will install for example crm, while it's being already tested on `INCLUDE=applications`.

**Comment by StefanRijnhart** [comment]
@pedrobaeza in 'no_applications' mode, the dependencies such as `crm` are pre-installed in the first pass but not tested.

Same for 'localizations' mode. In 'applications' mode, no module is preinstalled. Instead, all applications and their dependencies are tested.

This way, we cover the tests of all modules.

**Comment by pedrobaeza** [comment]
Ah, OK. The problem with this is runbot, as it expects to have one environment with TESTS=1. Please declare on the line you consider more appropiate (I think the `non_applications` to have the maximum number of installed modules.

**Comment by mreficent** [comment]
There is no overlap possible in **testing** as the new scripts have taken into account that.

**Comment by MiquelRForgeFlow** [comment]
Right. Why wasn't there TESTS=1 before? 🤔

**Comment by StefanRijnhart** [comment]
I added TESTS="0" to the no_applications job

**Comment by pedrobaeza** [comment]
It should be `TESTS="1"` AFAIK

**Comment by StefanRijnhart** [comment]
Got it wrong in the mail but right in the code ;-)

**Comment by pedrobaeza** [comment]
OK, thanks!

**Comment by MiquelRForgeFlow** [comment]
You should delete the link to the deleted branch on MQT. I thought you deleted before :S

**Comment by StefanRijnhart** [comment]
Yes, I do that sometimes. I reset against the remote branch, on a different system, before fetching. I destroyed a number of fixes now. It will have to wait until I'm in the office again.

**Comment by StefanRijnhart** [comment]
I reapplied the changes from memory

**Comment by StefanRijnhart** [comment]
Ah Runbot. The gift that keeps on giving.
```
Unable to find image 'oca-ocb:30b903e_2' locally
docker: Error response from daemon: repository oca-ocb not found: does not exist or no pull access.
See 'docker run --help'.
```

**Comment by pedrobaeza** [comment]
@moylop260 any hint about the runbot error?

**Comment by moylop260** [comment]
I have created a commit with the fix for runbot

**Comment by StefanRijnhart** [comment]
thanks @moylop260! I'm now excluding base_gengo to remove the breaking warning.

**Review by pedrobaeza — APPROVED** [review]
You made it!

**Comment by StefanRijnhart** [comment]
Hurray! Thanks everyone!

**Pull request merged**
