### PR TITLE
[9.0] disable autoinstall

### PR DESCRIPTION
**Pull request by hbrunn**
This is a cherry pick of #133 and #166, with my own addition of not autoinstalling auth_signup. No upstream PR for obvious reasons

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Surprisingly, website_portal does not seem to depend on portal so changing the dependencies of website_portal_sale seems just right. Now, a more pedantic person than me would suggest not to add a dependency on portal but instead change the existing dependency of website_portal_sale on sale into a dependency on 'portal_sale' but technically, that works out the same.

**Comment by pedrobaeza** [comment]
Can you please explain why do you need to add such dependency on website_portal_sale?

**Comment by StefanRijnhart** [comment]
@pedrobaeza it has a dependency on xmlids from the portal_sale module, which is not a problem because portal is autoinstalled up until this change and portal_sale is installed as a glue module automatically. Now that portal is no longer autoinstalled, the dependency has to be made explicit otherwise the website_portal_sale module will break.

**Review by pedrobaeza — APPROVED** [review]
Thanks for the explanation. Indeed, I remember now that my colleague has made this PR trying to improve the situation: https://github.com/odoo/odoo/pull/14777

**Comment by hbrunn** [comment]
two approves, 7 days - can one of you do the honors @pedrobaeza @StefanRijnhart ?

**Comment by yajo** [comment]
Hi everyone, just letting you know this broke OCB build of OCA/website.

**Comment by hbrunn** [comment]
then website should fix its dependencies

**Comment by yajo** [comment]
Not actually dependencies, other things, but it will be fixed soon and linked here, don't worry.

**Comment by pedrobaeza** [comment]
Fixed here: https://github.com/OCA/website/pull/306

**Pull request merged**
