### PR TITLE
Find and replace timezone-naive date defaults

### PR DESCRIPTION
**Pull request by veloutin**
This is a search and (manual) replace of time.strftime calls used for default
values of date fields instead of fields.date.context_today.

This fixes problems that show near day breaks, when UTC and local times have a different day, and causes the wrong day to be used.

### CODE REVIEW

**Comment by veloutin** [comment]
needs review!

**Comment by gurneyalex** [comment]
@veloutin: could you add a link to the upstream PR?

**Comment by veloutin** [comment]
Upstream: https://github.com/odoo/odoo/pull/6586

**Comment by veloutin** [comment]
Rebased on 7.0 to fix a merge conflict

**Comment by veloutin** [comment]
Runbot failure: except_osv: ('Google Contacts Import Error!', 'Please install gdata-python-client from http://code.google.com/p/gdata-python-client/downloads/list')

**Comment by gurneyalex** [comment]
looks good to me. I restarted the runbot build.

**Comment by gurneyalex** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
