### PR TITLE
[FIX] fix the mode readonly on image widget

### PR DESCRIPTION
**Pull request by sebastienbeau**
Hi, the readonly mode is broken on the image here is the fix.
The check if the readonly mode was active was simply forgotten.

Thanks

A PR have been done on odoo #1812

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: 

BTW I have checked that the bug is still present in v8 now (2014/08/17 for archive) so there is no fix to backport.

**Comment by pedrobaeza** [comment]
:+1:

Thanks for the fix.

**Comment by gurneyalex** [comment]
:+1:

**Comment by rvalyi** [comment]
Hello,

seems OpenERP SA will merge only the PR we merge in OCB but without acknowledging it. Well joking hopefully, still this one has been merged now in 7.0 so be careful with coming upstream merges:
https://github.com/odoo/odoo/commit/3b901f0aa03b084e1700c2f43ee89435465b06b2

**Comment by pedrobaeza** [comment]
Diff seems to be the same, so it seems there's not going to be any problem.

**Pull request merged**
