### PR TITLE
[FIX] return _auto_init's result

### PR DESCRIPTION
**Pull request by hbrunn**
upstream PR: https://github.com/odoo/odoo/pull/5204

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is there any issue for this?

:+1:

**Comment by hbrunn** [comment]
I encountered this when I wrote https://github.com/OCA/web/pull/83 and wanted the indicator field to be stored with triggers - that currently not possible because _auto_init doesn't pass through the todo to recompute the stored field on ir.filters

**Comment by pedrobaeza** [comment]
Thanks for the info, but if this is not merged upstream, we will have an OCB compatible only module, doesn't it?

**Comment by hbrunn** [comment]
That's why I made it a non-stored field for now. The performance hit is not bad. But I'd like to propose this just because it's wrong the way it is

**Comment by pedrobaeza** [comment]
Indeed, this kind of bugs make bottlenecks when you want to do some advanced developing. Anyways, the upstream PR is proposed again 8.0, and it's not mergeable. Have you seen it?

**Comment by hbrunn** [comment]
that's what github says. given that the odoo-devs never merged anything I proposed as it was but commited the diff, I don't see a reason to make it apply cleanly

**Comment by pedrobaeza** [comment]
OK, diff can be applied as you says.

**Comment by hbrunn** [comment]
fixed in https://github.com/odoo/odoo/commit/323233dd028b9db3e28faca65a89ec569738145b

**Pull request closed without merging**
