### PR TITLE
[FIX] portal: Restores auto_install for portal module

### LINKED ISSUE #682: [10.0] Test build fails on OCB but passes on Odoo
PR: https://github.com/OCA/project/pull/329
Log: https://travis-ci.org/OCA/project/jobs/289429902#L1292

It is related to `project_issue` and the `portal` modules.
Any ideas why?

### PR DESCRIPTION
**Pull request by pedrobaeza**
As discussed in #682, this is making tests to fail, so better to leave it as is.

Partial revert of #650

Alternative solution to #684

Closes #682

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Travis error:
```
odoo.addons.website_event.tests.test_ui: skipped 'PhantomJS not found'
```

**Comment by StefanRijnhart** [comment]
Restarted Travis

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Green!

**Comment by pedrobaeza** [comment]
Can we merge this for solving red Travis in other PRs/repositories?

**Comment by StefanRijnhart** [comment]
There you go!

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
