### PR TITLE
Fix 'report_webkit' module support real mako again. 

### PR DESCRIPTION
**Pull request by codingforfun**
Port parts of the original 7.0 code to 8.0 to let the module support real Mako again. 
Mapping jinja2 to mako is way to limited to support all Mako features used previously. 
Fix some minor bugs too. 

From discussions among the community it seams this module will be deprecated and unsupported in the future anyway so it's mostly useful to support old reports previously written for v7 during a transition period. 
Therefore we think the current state of the module in core is not very useful because it breaks this support without making any noticeable improvements. 

This is our proposal to make things work again.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I have tried and it's working, and it's a must have if you are using python code embedded on webkit reports, so for me it's a :+1:

Have you made the same proposal to upstream odoo?

**Comment by codingforfun** [comment]
@pedrobaeza 

> Have you made the same proposal to upstream odoo?

No.

**Comment by pedrobaeza** [comment]
You should then, because it's OCB policy to at least try to get the patch included in upstream Odoo.

**Comment by codingforfun** [comment]
@pedrobaeza 
I made another PR against upstream. Unfortunately I had to make another branch and rebase because OCB is so much ahead.

**Comment by pedrobaeza** [comment]
The best technique is to cherry-pick the commit. Can you please provide here the link for the upstream patch?

**Comment by codingforfun** [comment]
> Can you please provide here the link for the upstream patch?

Was right above my comment.
https://github.com/odoo/odoo/issues/8265

**Comment by StefanRijnhart** [comment]
Can anyone clarify what the rationale of the original change (mainly here: https://github.com/odoo/odoo/commit/49b1fa4b) was? Especially the security bit.

**Comment by dreispt** [comment]
This allows to have reports designed for OCB that don't work for Odoo.
AFAIK that is a line that OCB doesn't cross.
Probably it's wiser to wait for some feedback from the upstream PR before deciding here.

**Comment by codingforfun** [comment]
Looks like there is already a lot in OCB that doesn't work in Odoo ;-)

**Comment by codingforfun** [comment]
Note I changed the base of the branch to upstream/8.0 and did a forced push to have less work maintaining both pull requests. Please fetch and reset your local branch before testing if you checked out before.

**Comment by codingforfun** [comment]
@dreispt As I understand this, the preferred way of writing reports in odoo8 is using QWeb. However this means rewriting existing reports. So the sole purpose of this module may be to maintain backwards compatibility to existing reports that used to work with v7. But this backwards compatibility is also broken by switching from mako to jinja2, because we need to rewrite reports to support jinja2 anyway. Since this makes the module useless in fact in its current state in core, I think it would be ok  to cross this border in this case for compatibility reasons. 

Another option could be to make a copy of it like report_mako_webkit and make it another OCA add-on.

**Comment by pedrobaeza** [comment]
Yeah, have it as a module that can be installed in any database (odoo/OCB) can be the best option. Is this isolation possible?

**Comment by codingforfun** [comment]
The upstream PR has been rejected.

**Comment by pedrobaeza** [comment]
Can you make then a module called _report_webkit_mako_ with this functionality?

**Comment by codingforfun** [comment]
@pedrobaeza I can check how much work this would be. But it should be possible and maybe is the best idea.

**Comment by pedrobaeza** [comment]
Yes, please try it.

**Comment by pedrobaeza** [comment]
@codingforfun, have you made any progress on isolating this into a module?

**Comment by codingforfun** [comment]
@pedrobaeza not yet, but a colleague of mine is starting continuing this task just now

**Comment by pedrobaeza** [comment]
Great!

Let me know to test whatever you need.

**Comment by codingforfun** [comment]
Closing since we agreed it would be better to add this functionality in a separate out-of-core module. 
We're working on that an opening another PR soon.

**Pull request closed without merging**
