### PR TITLE
[IMP] Add language eu_ES Basque / Euskara

### PR DESCRIPTION
**Pull request by agaldona**
PR in Odoo : https://github.com/odoo/odoo/pull/8346

### CODE REVIEW

**Comment by oihane** [comment]
Great! :+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by Daniel-CA** [comment]
:+1:

**Comment by oihane** [comment]
It has been merged by @mart-e in https://github.com/odoo/odoo/commit/db6514ea48bee9cec631bb4e457bc76d84fd20ee

**Pull request closed without merging**
