### PR TITLE
#233: the return

### PR DESCRIPTION
**Pull request by lepistone**
#233 is marked as merged, but mysteriously it isn't.

I am here proposing the same branch and commit of the corresponding PR that @lmignon made on odoo/odoo#5620.

### CODE REVIEW

**Comment by lmignon** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
I know this was reviewed before, but I am wondering: why only in __create_ and not in __write_? https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L3878

**Comment by StefanRijnhart** [comment]
@lepistone: still curious (see previous comment)

**Comment by guewen** [comment]
My feeling is that it should be done in `_write` too even if it is not failing with geoengine for some reasons. It seems more correct to me to use the `_symbol_set` in both cases.

**Comment by yvaucher** [comment]
I know it works with it :+1: 

Nevertheless _symbol_set being equal by default to (_symbol_c, _symbol_f) and _symbol_c is by default '%s' it should not harm to change the write as well.

**Comment by lmignon** [comment]
I agree with @guewen and @yvaucher we should also use `_symbol_set` in `_write`

**Comment by lepistone** [comment]
Hi! I am unsure about the issue of `_write`, but I agree there's no harm in doing so.

I re-submitted @lmignon's branch, so I can't push to it to add `_write`. Could you please do it @lmignon?

**Comment by lmignon** [comment]
@lepistone done but not tested... Let's see what travis says

**Comment by lmignon** [comment]
@guewen @lepistone @yvaucher  I've updated the original PR to use the symbol_c everywhere into openerp/models.py

**Comment by StefanRijnhart** [comment]
Travis seems pretty happy! :+1:

**Comment by lepistone** [comment]
thanks!

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
