### PR TITLE
update account_invoice.py to fix issue #127

### PR DESCRIPTION
**Pull request by scigghia**
as proposed time ago on launchpad, fix for https://github.com/OCA/OCB/issues/127

### CODE REVIEW

**Comment by giudalo** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
In favour, as reviewed here: https://code.launchpad.net/~scigghia/ocb-addons/7.0_prop_supplier_invoice_number/+merge/208934. Sorry for the double work as the original attempt was not merged and thanks for trying again! Can you link to the upstream pull request though?

**Comment by pedrobaeza** [comment]
:+1: for me too

**Comment by scigghia** [comment]
hi @StefanRijnhart did you mean this https://bugs.launchpad.net/ocb-addons/+bug/1286483?

**Comment by StefanRijnhart** [comment]
No, you need to propose the same change to upstream Odoo on GitHub and link the proposal back here.

**Comment by scigghia** [comment]
ops, ok then :)

i'm going on it

**Comment by scigghia** [comment]
here upstream PR https://github.com/odoo/odoo/pull/4733
is this ok? :)

**Comment by StefanRijnhart** [comment]
Yes. Only now I noticed that you reintroduced the defensive checking for falsy values which is implicit in the Python construction. Can you adopt the original change

```
ref': inv.reference or inv.supplier_invoice_number or inv.name,
```

**Comment by scigghia** [comment]
done

**Comment by StefanRijnhart** [comment]
Thanks. Can you update the upstream PR as well?

**Comment by scigghia** [comment]
done

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Comment by scigghia** [comment]
Hi, is this patch ready for merge?

**Comment by scigghia** [comment]
thank you @StefanRijnhart :)

**Comment by StefanRijnhart** [comment]
You're welcome! Sorry for the delay

**Pull request merged**
