### PR TITLE
Fixes #2261 : should now work when a fiscal position replaces 1 tax by s...

### PR DESCRIPTION
**Pull request by alexis-via**
Should now work when a fiscal position replaces 1 tax by several taxes (for example : Fiscal position "Intra-EU B2B" in l10n_fr)

### CODE REVIEW

**Comment by clonedagain** [comment]
Just for my information, is it broken in v7 too?

**Comment by alexis-via** [comment]
@clonedagain 
No, this bug is only in v8 if you use the map_tax with the new API (it doesn't happen when you use map_tax() through the old API, that's why you don't see this bug on product_id_change of purchase.order)

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by yvaucher** [comment]
I close this as merged by @odony
https://github.com/odoo/odoo/commit/7508b7cd9ce07fab3e968e049dbee8fe314abae8

**Pull request closed without merging**
