### PR TITLE
[9.0] yaml_import: fix use of onchange

### PR DESCRIPTION
**Pull request by gurneyalex**
This is a port of odoo#9896 to OCB

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:  thanks.

**Comment by njeudy** [comment]
Ok just tested here :+1:

**Comment by sebastienbeau** [comment]
:+1:  thanks for the fix

**Comment by lepistone** [comment]
Thanks. I bumped the upstream because I'd love to hear something from odoo for such a big change. I suggest we wait another few days and merge in OCB next week.

https://github.com/odoo/odoo/pull/9896#issuecomment-165721391

**Comment by lepistone** [comment]
Merged upstream.

**Pull request merged**
