### PR TITLE
[FIX] mail: read more show original message

### PR DESCRIPTION
**Pull request by mdietrichc2c**
New PR to add https://github.com/odoo/odoo/pull/3295 to OCB (as Odoo will not add it to the stable 7.0 version, only in 8.0).

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
Runbot error unrelated.

**Comment by vrenaville** [comment]
:+1: I have test the fix and it's work as expected

**Comment by pedrobaeza** [comment]
Are security concerns mentioned by @gurneyalex solved?

**Comment by mdietrichc2c** [comment]
From @vrenaville : he tried to inject JavaScript through the mail, and it didn't bypass present security.

**Comment by pedrobaeza** [comment]
OK, I would like to hear @gurneyalex's opinion here, but for me :+1:

**Comment by gurneyalex** [comment]
:+1: for me.

**Comment by yvaucher** [comment]
I proceed with the merge as @gurneyalex concern on security was replied

**Pull request merged**
