### PR TITLE
[FIX] add taxes in invoice lines before validating them

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please make the corresponding PR upstream.

**Comment by damdam-s** [comment]
@pedrobaeza done : https://github.com/odoo/odoo/pull/7988

**Comment by pedrobaeza** [comment]
We can't differ here from the upstream because people can rely on this data to design the tests and thus there will be a difference between testing OCB and Odoo itself, so :-1:

**Comment by pedrobaeza** [comment]
Closing according comments.

**Pull request closed without merging**
