### PR TITLE
fix odoo/odoo#4792 signature mismatch on price_get

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:  I agree, the id is expected, not the object.

**Comment by gurneyalex** [comment]
odoo PR is https://github.com/odoo/odoo/pull/4793

:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
We can merge then.

**Pull request merged**
