### PR TITLE
[FIX] .travis.yml: Install original requirements.txt

### PR DESCRIPTION
**Pull request by moylop260**
Now the MQT/requirements.txt was deprecated then show a error of file not found

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's still red. Shouldn't we install both (MQT and OCB requirements.txt)?

**Comment by kenvac** [comment]
@moylop260 could you please rerun the travis test? It is currently timing out and hence failing. 
Once it passes the test may be @pedrobaeza will review and merge it.

**Comment by moylop260** [comment]
The issue [The job exceeded the maximum time limit for jobs, and has been terminated](https://github.com/travis-ci/travis-ci/issues/5881) is unrelated with the focus of this PR.

I have created the following issue:
 - https://github.com/OCA/OCB/issues/639

Ideas to fix and contributions are welcome

IMHO this PR could be merged.

**Comment by Daniel-CA** [comment]
Can someone merge this PR? As @moylop260 said this resolves the Travis error that we are having in OCB 8.0 branch.

Could not open requirements file: [Errno 2] No such file or directory: '/home/travis/maintainer-quality-tools/travis/requirements.txt'

**Comment by pedrobaeza** [comment]
OK, there's a timeout error, but this is other thing. Merging.

**Pull request merged**
