### PR TITLE
8.0 product 48 test therp

### PR DESCRIPTION
**Pull request by NL66278**
Prevent errors when running test on product module. Solves #7320

Is it still needed to make an upstream PR?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I see some things mixed. Why the JS change?

**Comment by NL66278** [comment]
@pedrobaeza My mistake. Had the intention to use a clean ocb branch as base for the PR, but it actually contains an unrelated merge. I will correct this.

**Comment by NL66278** [comment]
@pedrobaeza Sorry was occupied with some other stuff. Changed it now to have anly changes for the problem at hand.

**Comment by NL66278** [comment]
The build is going wrong because of this: The command "sudo wget http://downloads.sourceforge.net/project/wkhtmltopdf/archive/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb -P /tmp/" failed and exited with 8 during .

I saw somewhere that wkhtmltopdf moved, but I have no power to change this.

**Comment by pedrobaeza** [comment]
:+1: 

I see this also interesting to be propose upstream

**Comment by StefanRijnhart** [comment]
Can you show us where the tests fail? Odoo and OCA runbots are green even without this patch.

**Comment by StefanRijnhart** [comment]
If you rebase, the link to wkhtmltopdf should be fixed.

**Comment by NL66278** [comment]
Now I get another error which seems unrelated, and with an error log exceeding 4 Mb. Is it still possible to test OCB?

**Comment by StefanRijnhart** [comment]
I restarted Travis, and your commit is now green. But it was already green before your change, so I don't see the problem with the tests.

**Pull request closed without merging**
