### PR TITLE
[REF] add hook to ease overriding the merge of automatic po

### PR DESCRIPTION
**Pull request by florian-dacosta**
In some case we do not want to merge purchase orders. It would be nice to have a way to custom that easily.

Thanks.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Have you made the same PR to upstream Odoo?

**Comment by florian-dacosta** [comment]
yes
https://github.com/odoo/odoo/pull/6205

**Comment by pedrobaeza** [comment]
OK, let's wait then if it's accepted there, because it's not desirable to have code that works only on OCB, but not on official one.

**Comment by gurneyalex** [comment]
hello @florian-dacosta could you please rebase your branch?

**Comment by StefanRijnhart** [comment]
:-1: API change as @pedrobaeza said.

**Pull request closed without merging**
