### PR TITLE
[8.0][FIX] ir_sequence: add support for PG 10

### PR DESCRIPTION
**Pull request by sergiocorato**
Description of the issue/feature this PR addresses: postresql 10 is not supported from ir_sequence

Current behavior before PR: ir_sequence give error in access

Desired behavior after PR is merged: postgresql 10 is supported

This MP is a backport from 9.0 https://github.com/odoo/odoo/commit/fa5ee6ed2634b1a5b4388efb2c6ab6ae80356f28 (same bugfix is fixed for 10.0 and 11.0)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why do you close this PR?

**Comment by sergiocorato** [comment]
I saw another problem in a custom module, so I can't assure that there
aren't other bugs that I don't know using Odoo v.8 with PG 10 (I think no
one is using this configuration), so I decided to keep PG 9.6

Sergio Corato
cel. wsp +39 348 6622 725

2018-07-03 11:58 GMT+02:00 Pedro M. Baeza <notifications@github.com>:

**Comment by pedrobaeza** [comment]
OK, thanks for explaining. I recommend you to try to go to upper versions. You can migrate with OpenUpgrade.

**Comment by sergiocorato** [comment]
ASAP :D

Il mar 3 lug 2018, 12:40 Pedro M. Baeza <notifications@github.com> ha
scritto:

**Pull request closed without merging**
