### PR TITLE
Fix duplicate line creation

### PR DESCRIPTION
**Pull request by dreispt**
*(Upstream PR https://github.com/odoo/odoo/pull/18599)*

Based on leahim's solution (https://github.com/odoo/odoo/issues/5629#issuecomment-134980176)
Fixes https://github.com/odoo/odoo/issues/5629
Fixes https://github.com/odoo/odoo/issues/7391

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Wow! Let me test this in some of my setups

**Comment by dreispt** [comment]
@StefanRijnhart Please share your conclusions. Since it is low risk, I deployed this in production, but am not convinced that the issue was fixed...

**Comment by StefanRijnhart** [comment]
It's difficult to reproduce, isn't it? I seem to remember a clear way to encounter this problem but it has escaped me now.

**Comment by messakali** [comment]
If I remember I was facing it in this situation or similar :
- Add an new item in o2m list
- Click on an other button than "save" that raise an exception, a new item was added every time I click on the button

**Comment by dreispt** [comment]
@StefanRijnhart I'm for merging this fix, as it is just on the webclient js and has low risk.

**Comment by StefanRijnhart** [comment]
@messakali You see, that's what I thought too. But I tried to reproduce it (forcing a server side exception on confirming a move or a sales order) and the problem does not occur.

**Pull request closed without merging**
