### PR TITLE
Subscribe before sending first message

### PR DESCRIPTION
**Pull request by yajo**
I am forwarding here https://github.com/odoo/odoo/pull/8723 presuming it will get ignored.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
See upstream comment

**Comment by yajo** [comment]
Yes, let's keep this on hold until upstream decides.

**Comment by StefanRijnhart** [comment]
Upstream discussion clarified. Thanks for your PR @yajo. Still a bit worried about the unnecessary whitespace change. I know these changes fix style issues, but they can cause extra conflicts in the OCB merging process. Would you consider correcting these?

**Comment by yajo** [comment]
https://github.com/odoo/odoo/pull/8723 merged upstream, so I'm closing this.

**Pull request closed without merging**
