### PR TITLE
7.0 - Fix the purchase order report label when the state is sent

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

Thanks!

**Comment by hbrunn** [comment]
did you propose the same to upstream? :+1: for the change as such

**Comment by ghost** [comment]
@hbrunn, I did not propose this change to odoo/odoo because they might not consider it because it impacts only v7.

**Comment by yvaucher** [comment]
@dufresnedavid still can you try to make your fix on official branch, they might fix.

**Comment by ghost** [comment]
@yvaucher created the upstream pull request. https://github.com/odoo/odoo/pull/8501 Let's see how long it takes. My guess is it will never pass.

**Comment by yvaucher** [comment]
@dufresnedavid This is mostly used as a reference as we don't want to differ too much from upstream

Thanks

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
