### PR TITLE
This PR fixe issue #3258 against 7.0 like PR #81

### PR DESCRIPTION
**Pull request by petrus-v**
Here the PR to fix issue #3258 on odoo 7.0 like PR #81 already merged on 8.0 branch.

This issue should be related in a technical documentation, I wonder if OCA maintains the technical odoo documentation ?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks!

:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
As reviewed on #81 :+1:. Thanks for the backport!

**Comment by StefanRijnhart** [comment]
Fast tracked this one because of previous PR on 8.0. Oh, and there is no technical documentation on OCB specifics yet, but maybe you can start something on the wiki?

**Pull request merged**
