### PR TITLE
[9.0][FIX] travis file: enable runbot

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Let's see if with this PR, runbot is fixed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The red on runbot is because:

```
2018-04-05 14:09:42,207 156 WARNING openerp_test openerp.addons.base_gengo.wizard.base_gengo_translations: Gengo library not found, Gengo features disabled. If you plan to use it, please install the gengo library from http://pypi.python.org/pypi/gengo
```

We can add that library in the requirements.txt for avoiding it.

**Comment by MiquelRForgeFlow** [comment]
There: https://github.com/OCA/maintainer-quality-tools/pull/536

**Comment by pedrobaeza** [comment]
No, I'm talking here in OCB.

**Comment by MiquelRForgeFlow** [comment]
Ok 😅 Updated. Let's see now.

**Comment by MiquelRForgeFlow** [comment]
Runbot is :green_apple: :green_apple:

**Comment by pedrobaeza** [comment]
Cool, let's work on the split in v8 and then transfer the result here.

**Comment by MiquelRForgeFlow** [comment]
I think you could merge this. The Travis is green in v9 because the time to compute is 46 min 18 sec. And we don't know when the split v8 will be ready.

**Comment by pedrobaeza** [comment]
OK, merging.

**Pull request merged**
