### PR TITLE
Restart procurement workflow when stock.move cancel_assign method is cal...

### PR DESCRIPTION
**Pull request by florian-dacosta**
In a simple installation with modules procurement and sale : 
We confirm a sale order for a product having as method of procurement : 'make_to_stock' (and supply method 'buy').
If we have enought stock, when the scheduler runs, the delivery order will become available. 
If for any reason, I cancel the reservation of the product (clicking on "cancel assign" button on the stock move), the procurement state does not change (it stays on 'ready' state).
So when the scheduler runs again, The state of the delivery order will not change to available. And without a user action, the delivery order won't become available.

To solve this issue, I have to delete the procurement workflow and create a new one because the is no way to go back from 'ready' to 'confirmed' without canceling the stock moves.

I am not sure I am doing it the right way, but I can change if needed!
What do you think?

### CODE REVIEW

**Comment by yvaucher** [comment]
@florian-dacosta That's an old one. But, is there an issue reported on odoo ?

**Comment by florian-dacosta** [comment]
Sorry I am very late to reply!

I just have made the PR on Odoo.
https://github.com/odoo/odoo/pull/6237

The steps to reproduce the bug : 
1) I create an sale order with 1 product which is available in stock.
2) Once the sale order is confirmed, I run the scheduler so my delivery order goes to 'ready to deliver'.
3) I change the stock of my product to 0 and I cancel the avaibility of the delivery order (button cancel_assign on the stock.move)
4) I have an incoming shipment of the same product, I validate it, so my product is available in stock once again.
5) I run the scheduler so my delivery order goes to 'ready to deliver' again

**Comment by sebastienbeau** [comment]
Thanks for the fix :+1:

**Comment by pedrobaeza** [comment]
Seeing the explanation, seems correct, so I approve and merge this.

**Pull request merged**
