### PR TITLE
[IMP] point_of_sale: handle products tracked as lots

### PR DESCRIPTION
**Pull request by chienandalu**
Backport patch from `11.0`that drastically improves the usability of lots in the Point of Sale frontend.

cc @Tecnativa
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
thanks! Can you point to the commits in the odoo tree that you backported?

**Comment by chienandalu** [comment]
Hi, @StefanRijnhart 

This is the v11 commit: https://github.com/odoo/odoo/commit/025d9432a1dfc1db484e9e65d2748ed91d67ca26

My second commit fixes a bug introduced by it. That bug was fixed by a deep remodeling in v11 that it's not going to fit in a backport anyway: https://github.com/odoo/odoo/commit/8f39c652c65c81d87503d64eeef0da3e0048ffc9

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the pointers!

**Comment by pedrobaeza** [comment]
@chienandalu please rebase to get a green build.

**Comment by chienandalu** [comment]
It's green now

**Comment by pedrobaeza** [comment]
@chienandalu please refresh me then what is the status of the OPW ticket. What has been merged and what hasn't.

**Comment by chienandalu** [comment]
We're still discussing about the point of the issue. Nothing has been merged into 10.0 yet

**Comment by pedrobaeza** [comment]
OK, let's see if they make a move during this week before merging this.

**Review by pedrobaeza — APPROVED** [review]
I'm going to cherry-pick the commit, as the branch contained undesired commits.

**Comment by pedrobaeza** [comment]
Cherry-picked in fe8ef4ad0c5bd121965c2b16ad244ff89d81816a and ece5db8e1721c9b84e594fb8ef6aae867c415996

**Pull request closed without merging**
