### PR TITLE
Bugfix/5987 statusbar colors

### PR DESCRIPTION
**Pull request by phuihock**
Upstream PR odoo#5987
- first PR to OCB. Please excuse me if there's any prerequisites not met.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, @phuihock, thanks for your PR. There are several things to fix:
- Deactivate automatic line trimming to make the diff smaller and to avoid future conflicts.
- In OCB, the CLA you are sending to Odoo is not needed. We have our CLA that you have already signed. So, you can't just cherry-pick the commit from Odoo.

**Comment by phuihock** [comment]
OK, should I close this PR and resubmit?

**Comment by pedrobaeza** [comment]
No, you can fix your branch and force push over this same PR.

**Comment by phuihock** [comment]
I use the same branch to create PR for both OCA and odoo. Closing this. Will resubmit.

**Pull request closed without merging**
