### PR TITLE
prevent the constraint to be recreated on update

### PR DESCRIPTION
**Pull request by lepistone**
This fixes https://github.com/odoo/odoo/issues/2112 at least for move
lines. If the constraint is not written exactly like that, the next time
we update the module OpenERP does not recognize it and drops and
recreates the constraint. This is dangerous, and takes a long time in a
big table.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the investigation. :+1:

**Comment by lmignon** [comment]
:+1:  seems to be a safe way to fix this issue for move... and significantly reduces time required when we update the module

**Comment by gurneyalex** [comment]
I agree on the principle, although I'm concerned this fix could be dependent on the version of Postgresql.

**Comment by lepistone** [comment]
@gurneyalex I agree with you, but I'm confident that in the worst case we get back to where we started from.

Or you see a risk of it really breaking in some Postgresql setup?

**Comment by gurneyalex** [comment]
nope, hence :+1:

**Pull request merged**
