### PR TITLE
[IMP] Make many2many widgets in listview usable for one2many

### PR DESCRIPTION
**Pull request by codingforfun**
Description of the issue/feature this PR addresses:
I think in JS i.e. from the client perspective, the data necessary to render `one2many` fields in list view columns is the same as for `many2many`. Therefore the same preprocessing should be applied to make widgets existing for `many2many` usable for `one2many`. 
I tested this with a one2many field, where I applied widget `many2many` to get a list of names of linked items rendered instead of the linked item count. 

``` xml
<tree ....>
    ....
    <field name="assigned_users" widget="many2many"/>
    ....
</tree>
```

Please comment. Although I tested this I'm not sure if I'm aware of all possible implications. In my opinion  `one2many` and `many2many` fields have compatible data representation here, but maybe I overlooked something.

Current behavior before PR:
- Widgets build for `many2many` in list views aren't usable for `one2many` because the necessary preprocessing of the record data for the column is missing.

Desired behavior after PR is merged:
- Widgets build for `many2many` in list views are usable for `one2many` columns.
## 

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Are you aware of https://github.com/OCA/web/pull/319?

**Comment by codingforfun** [comment]
@pedrobaeza 
No I didn't know this. 
Thanks. This was what I was basically aiming at. 

@hbrunn does the same trick here: 
https://github.com/hbrunn/web/blob/8.0-web_widget_one2many_tags/web_widget_one2many_tags/static/src/js/web_widget_one2many_tags.js#L85

But since he otherwise also doesn't customize the list view widget but uses the default one also, this to me seams to be a strong indicator to fix this in the core to have a more generic way of customization of x2many fields in list view.

**Comment by pedrobaeza** [comment]
Why don't you improve his PR for getting a full feature module?

**Comment by codingforfun** [comment]
Btw. I didn't make a upstream PR yet because I wanted to get opinions first.

**Comment by codingforfun** [comment]
> Why don't you improve his PR for getting a full feature module?

What do you mean by `full feature module`? 

I would rather propose to make both changes. I think this PR is a general patch to get the necessary data into the column. @hbrunn builds a specific widget. I think there are possible more widgets to build for one2many if the data is present. Therefor I wouldn't mix this. 
However if we agree on this PR. The workaround in the other one could be removed of course.

**Comment by pedrobaeza** [comment]
OK, I understand about the generic one2many, but this should be done in a module that the @hbrunn's module can use it, not in OCB, because again this will be hardly accepted on upstream Odoo.

**Comment by codingforfun** [comment]
> [...] again this will be hardly accepted on upstream Odoo

Why don't you think so? I think this is the right place and has just been forgotten in upstream. If no one says this is basically wrong from the technical perspective I would try this. 

I thought of making this a separate module, but this module would extend the render() only to basically duplicate the existing code used for `many2many`. This isn't a very nice solution I think.

**Comment by codingforfun** [comment]
and btw. I don't introduce any signature changes this time ;-)
again, this change would be perfectly backwards compatible with vanilla odoo from upstream

**Comment by hbrunn** [comment]
I think it's worth trying to get this into upstream, but I share @pedrobaeza's doubts it's going to be accepted. Which doesn't matter in my opinion, because this is perfectly fine for OCB only I think.

So given you also provide an upstream PR, :+1:

**Comment by codingforfun** [comment]
@hbrunn 
here it is: https://github.com/odoo/odoo/pull/11282

**Comment by ivantodorovich** [comment]
:+1: and :+1: 

Although I think odoo needs to completely refactor that method and put widget/column specific logic inside each column class, to make it more easily extended by any type of widget.

**Comment by pedrobaeza** [comment]
OK, merging this one!

**Pull request merged**
