### PR TITLE
[9.0][FIX][hr_holidays] Allow to overlap different types

### PR DESCRIPTION
**Pull request by yajo**
Downstreaming odoo#11026 to OCB.

@Tecnativa

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Thanks

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by yajo** [comment]
It says `The job exceeded the maximum time limit for jobs, and has been terminated.` but no error so far

**Comment by pedrobaeza** [comment]
Again red, but I'm not sure tests finish. 49 minutes being executed!

**Comment by yajo** [comment]
Maybe I need to rebase to get some travis boosts? This is the same branch as upstream PR...

**Comment by pedrobaeza** [comment]
Well, you should always use a specific branch for OCB. But the test should last the same

**Review by pedrobaeza — APPROVED** [review]
This has been merged for v10 also in upstream

**Pull request merged**
