### PR TITLE
Do not mark message as read upon failure

### PR DESCRIPTION
**Pull request by jbq**
Yet mark ignored messages as seen.  Streamlines IMAP handling against
POP.

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
Hi,

Just to let you know that I proposed and discussed with odoo to include the same patch and they refused. So if we include it in OCB, we have to accept that it will never be accepted upstream.

**Comment by guewen** [comment]
Ref: https://bugs.launchpad.net/openobject-addons/+bug/1296724

**Comment by jbq** [comment]
IMHO it's the purpose of OCB to accept useful contributions that are not integrated upstream for some reason.  Regarding this specific patch, IMAP was not working the same as POP, so I streamlined the error processing in IMAP so that it becomes similar to the POP processing.

**Comment by yvaucher** [comment]
Usually, OCB is there to accept faster fixes that takes time to land in odoo.
But, I agree with @jbq in such case I think we want that kind of contrib to land in OCB.

**Comment by hbrunn** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1: but I think we should try with a new upstream proposal. This patch seems less intrusive than the OPW patch, and we can vouch support for this change upstream then.

**Comment by eLBati** [comment]
Some days ago I made the same upstream proposal: https://github.com/odoo/odoo/pull/5704

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
