### PR TITLE
Add fiscal period configuration in settings.

### PR DESCRIPTION
**Pull request by feketemihai**
Followup of Odoo reject of PR.

https://github.com/odoo/odoo/pull/22696/files

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by feketemihai** [comment]
I mage the PR but only after i saw there some modules on https://github.com/OCA/account-financial-tools that do the same think, i will migrate in the nearest future those to v11.

**Comment by StefanRijnhart** [comment]
Indeed, this is all part of the 'making accounting unusable in community' strategy in Odoo 11.0 and up, and I think having this in an OCA module is the best solution.

**Comment by astirpe** [comment]
@feketemihai please ping me when you publish that module!

**Comment by pmartineznetquest** [comment]
Hi all! 

We have developed a module to include these 2 date fields in odoo v11. But we have found other problems because of this constraint (and that's the reason we have not shared it yet): 

- If you close a period and you have a payment of an invoice outside this period the system raise an error, maybe because you are trying to add or write a Journal Entry although the payment date is in a valid period. 
- That means that you cannot register a payment after you have closed the period, and I think this scenario is going to happen in 99% of payments.
- And I haven't seen any module in v9 or v10 that solves this scenario.

We are thinking about changing this behaviour modifying the core, but does not to seem the best way.

Any ideas?
Thank you very much!
Pere
CC: @astirpe @feketemihai

**Comment by feketemihai** [comment]
@pmartineznetquest After i made this PR, i saw that there was already a module to add them, please see PR's:

https://github.com/OCA/account-financial-tools/pull/612
https://github.com/OCA/account-financial-tools/pull/615

for different types of locking...with 615 you can lock separately journals, permanently or not, or lock separate moves..

**Comment by pmartineznetquest** [comment]
Hi, @feketemihai, and thank you very much for the answer, 

I think is a very good idea to merge all the account lock features in a single module. I will wait for being merged. I have to check it all and see if it will solve the payment restriction scenario (a very common scenario, as far as I know). 

Thanks again!

Pere

**Pull request closed without merging**
