### PR TITLE
[7.0] On module update or init always update module list

### PR DESCRIPTION
**Pull request by Tonow-c2c**
On V 7.0 we want like V 8.0 https://github.com/OCA/OCB/pull/354/commits/f6db474ba3924f47a97631523f0669eb9991c4e5
Always update the modules list

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Still with v7!? OK for me about the change.

**Review by grindtildeath — APPROVED** [review]
Must have feature :+1:

**Comment by guewen** [comment]
> Still with v7!?

:sob:

**Review by guewen — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I have put a commit for fixing Travis file, but let's merge this directly meanwhile

**Pull request merged**
