### PR TITLE
[16.0][FIX] l10n_it_edi remove auto_install

### PR DESCRIPTION
**Pull request by sergiocorato**
Same logic of #1245 

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by primes2h — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I'm not sure about this one, as FacturX auto-installed seems for me a good one, having automatically the invoices done with Odoo imported when you upload the PDF.

**Comment by sergiocorato** [comment]
Well, I think that a module has to be autoinstalled only if it is a requirement in every situation.
If it's not required nor useful in some cases, forcing users to uninstall it and use other modules to stop its reinstallation, than make it optional.

**Comment by primes2h** [comment]
> I'm not sure about this one, as FacturX auto-installed seems for me a good one, having automatically the invoices done with Odoo imported when you upload the PDF.

I think that this comment explains well the reasons to disable autoinstall:  
https://github.com/odoo/odoo/issues/71190#issuecomment-847915516

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by marcelofrare — APPROVED** [review]
I think there are more advantages than disadvantages with:
'auto install': False 
for me it's ok

**Review by MarcoCalcagni — APPROVED** [review]
Yes

**Review by danall59 — APPROVED** [review]
OK, ASAP

**Comment by pedrobaeza** [comment]
I see you all Italian people approving this. Is there any special interest in your country for this?

**Comment by sergiocorato** [comment]
As reported by @SirAionTech , this result can be obtained by removing https://github.com/OCA/OCB/blob/40d1a584a059f1a8eb021699cefa8eb89f452a61/addons/l10n_it_edi/__manifest__.py#L15
I'll change the PR ASAP.

**Review by pedrobaeza — APPROVED** [review]
OK, this one is more focused.

**Pull request merged**
