### PR TITLE
[FIX] When using Postgresql 10.0 and above make sure you handle the sequences correctly. Backport of fa5ee6ed

### PR DESCRIPTION
**Pull request by daramousk**
See fa5ee6ed

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit authorship

**Comment by pedrobaeza** [comment]
FYI, this is the same as #769. First that preserves commit author will be merged.

**Comment by daramousk** [comment]
@pedrobaeza Changed the author.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@hbrunn I think you still maintain 8.0 customers, so this one can be interesting for you.

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
