### PR TITLE
[FIX] stock: fix AccessError on stock.quant while trying to resolve an inventory line linked to a package

### PR DESCRIPTION
**Pull request by tafaRU**
Upstream PR: https://github.com/odoo/odoo/pull/12512

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1: quants can only be written by admin.

**Comment by paolovalier** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Merged upstream and forward ported to 9.0 https://github.com/odoo/odoo/commit/e3954a3457bffd7c8e5ea09ac9c4802e3cd307dc

**Pull request closed without merging**
