### PR TITLE
[10.0][IMP] Improvements of VAT report and implementation TVA return …

### PR DESCRIPTION
**Pull request by ghost**
…charge backport

Description of the issue/feature this PR addresses:

fix some VAT issues for Swiss localisation

Current behaviour before PR:

some VAT tags and templates are missed.

The desired behaviour after PR is merged:

add new vat tags and templates. fix indentation

https://github.com/odoo/odoo/pull/25190

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Code review only.
Not an expert, but tested internally with @fclementic2c

**Comment by fclementic2c** [comment]
:+1:

**Comment by gurneyalex** [comment]
@oleksandrpaziuk is there a PR on odoo/odoo for this? If so please include the link in the description.

**Comment by ghost** [comment]
@gurneyalex Yes! Here it is https://github.com/odoo/odoo/pull/25190

**Comment by leemannd** [comment]
@OCA/core-maintainers the pr on odoo/odoo has been merged.
This one can be closed
https://github.com/odoo/odoo/pull/25190

**Pull request closed without merging**
